monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
  handlers:
    all_logs_file:
      type: stream
      path: '%app.log.file%'
      formatter: monolog.formatter.line
      channels: [ "!deprecation" ]
      level: notice

    main:
      type: fingers_crossed
      action_level: error
      handler: logs_by_service_error_stream
      excluded_http_codes: [ 404, 405 ]
      buffer_size: 50

    logs_by_service_error_stream:
      type: stream
      path: php://stderr
      level: error
      formatter: monolog.formatter.json

    logs_by_service_stream:
      type: stream
      path: php://stdout
      formatter: monolog.formatter.line
      level: info
      process_psr_3_messages: true
      channels: [ "!event", "!doctrine", "!deprecation" ]

    logs_by_service_stream_info_only:
      type: filter
      handler: logs_by_service_stream
      max_level: warning

    deprecation:
      type: stream
      channels: [ deprecation ]
      path: php://stderr

    critical_mailer:
      type: fingers_crossed
      action_level: critical
      handler: symfony_mailer

    symfony_mailer:
      type: symfony_mailer
      from_email: '%app.mail.tdt_from_email%'
      to_email: '%app.mail.email_admin_technique%'
      subject: '[%%datetime%%] %%extra.service_name%%.%%level_name%%: %%message%% %%context%% { "pid" : %%extra.pid%% }'
      level: critical
      formatter: monolog.formatter.html

when@test:
  monolog:
    handlers:
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ["!event"]

      logs_by_service_stream:
        type: "null"
      logs_by_service_error_stream:
        type: "null"
      all_logs_file:
        type: "null"
      critical_mailer:
        type: "null"
      symfony_mailer:
        type: "null"
