monolog:
  channels:
    - deprecation
  handlers:
    all_logs_file:
      type: rotating_file
      path: '%app.log.file%'
      formatter: monolog.formatter.line
      channels: [ "!deprecation" ]
      max_files: 180
      level: notice

    critical_mailer:
      type: fingers_crossed
      action_level: critical
      handler: symfony_mailer

    symfony_mailer:
      type: symfony_mailer
      from_email: '%app.mail.tdt_from_email%'
      to_email: '%app.mail.email_admin_technique%'
      subject: '[%%datetime%%] %%extra.service_name%%.%%level_name%%: %%message%% %%context%% { "pid" : %%extra.pid%% }'
      level: critical
      formatter: monolog.formatter.html

when@prod:
  monolog:
    handlers:
      instance-specific:
        type: rotating_file
        path: '%kernel.logs_dir%/%app.service_name%.log'
        formatter: 'monolog.formatter.line'
        channels: [ "!deprecation" ]
        max_files: 180
        level: info

when@dev:
  monolog:
    handlers:
      instance-specific:
        type: rotating_file
        path: '%kernel.logs_dir%/%app.service_name%.log'
        formatter: 'monolog.formatter.line'
        channels: [ "!deprecation" ]
        max_files: 180
        level: info

when@test:
  monolog:
    handlers:
      buffer:
        type: buffer
        handler: test
        level: debug
      test:
        type: test
