security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        S2low\Security\SecurityUser: 'auto'

    providers:
        certificate_user_provider:
            id: S2low\Security\SecurityUserProvider

        password_user_provider:
            id: S2low\Security\PasswordUserProvider

        chain_provider:
            chain:
                providers: ['password_user_provider', 'certificate_user_provider']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            stateless: false
            provider: chain_provider
            entry_point: S2low\Security\CustomAuthenticationEntryPoint
            custom_authenticators:
                - S2low\Security\FormLoginAuthenticator
                - S2low\Security\X509Authenticator
            logout:
                path: /deconnexion
                target: /connexion

    access_control:
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/login\.php, roles: PUBLIC_ACCESS }
        - { path: ^/deconnexion, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
