twig:
    file_name_pattern: '*.twig'
    debug: true
    cache: false
    auto_reload: true
    globals:
        webmaster: 'webmaster@s2low.docker.libriciel.fr'
        support_url: '/'
        release_note_url: '/'
        version_infos: 'Version 5.1.2 - Révision 341317 - Thu Jul 24 13:01:20 UTC 2025'
        url_index_ssl: '/'
        title: '%app.website_default_title%'
        s2low_banner: '/custom/images/bandeau_s2low.jpg'
        jqueryJsUrl: '/jsmodules/jquery.js'
        jqueryuiJsUrl: '/jsmodules/jqueryui.js'
        tedetisJsUrl: '/javascript/tedetis.js'
        bootstrapMinCssUrl: '/custom/styles/bootstrap.min.css'
        bootstrapThemeMinCssUrl: '/custom/styles/bootstrap-theme.min.css'
        styleBsCssUrl: '/custom/styles/style_bs.css'

when@test:
    twig:
        strict_variables: true
