twig:
    file_name_pattern: '*.twig'
    debug: true
    cache: false
    auto_reload: true
    globals:
        versionning: '@S2lowLegacy\Class\Versionning'
        webmaster: '%app.webmaster%'
        url_index_ssl: '/'
        versionInfoLabel: 'Version %%VERSION%% - Révision %%CI_BUILD_ID%% - %%BUILD_DATE%%'
        title: '%app.website_default_title%'
        s2low_banner: '/custom/images/bandeau_s2low.jpg'
        jqueryJsUrl: '/jsmodules/jquery.js'
        jqueryuiJsUrl: '/jsmodules/jqueryui.js'
        tedetisJsUrl: '/javascript/tedetis.js'
        bootstrapMinCssUrl: '/custom/styles/bootstrap.min.css'
        bootstrapThemeMinCssUrl: '/custom/styles/bootstrap-theme.min.css'
        styleBsCssUrl: '/custom/styles/style_bs.css'

when@test:
    twig:
        strict_variables: true
