include:
  - project: "libriciel/integration-continue/templates"
    ref: publish-container-to-registry@2.0.0
    file: '/jobs/publish-container-to-registry/publish-container-to-registry.yml'
  - project: "libriciel/integration-continue/templates"
    ref: security-check@1.3.2
    file: '/jobs/security-check/security-check.yml'
  - template: Code-Quality.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - component: $LIBRICIEL_CATALOG_PATH/renovate-runner/runner@1.4.0
  - component: $LIBRICIEL_CATALOG_PATH/software-release/publish-compose@2.2.0
  - component: $LIBRICIEL_CATALOG_PATH/sbom-manager/build@1.2.0
    inputs:
      compose_file: "docker-compose.yml"
      version_placeholder: "canary"

stages:
    - .pre
    - build
    - static-analysis
    - test
    - quality
    - deploy
    - staging
    - production

variables:
    CONTAINER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    POSTGRES_DB: s2lowdb
    POSTGRES_USER: s2lowuser
    POSTGRES_PASSWORD: s2lowpassword
    DATABASE_URL: "postgresql://s2lowuser:s2lowpassword@postgres:5432/s2lowdb?serverVersion=14&charset=utf8"
    PRODUCT: s2low

build:
  stage: build
  except:
    - tags
  tags:
    - docker-build
  script:
    - /bin/bash docker-resources/generate-manifest.sh > manifest.txt
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --target s2low_dev --pull -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

# Utiliser lors de la pose d'un tag pour que la construction n'utilise pas le cache
build_no_cache:
  stage: build
  only:
    - tags
  tags:
    - docker-build
  script:
    - /bin/bash docker-resources/generate-manifest.sh > manifest.txt
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --no-cache --target s2low_dev --pull -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}

lint:
  stage: static-analysis
  image : "$CONTAINER_IMAGE"
  variables:
    DONT_RETRIEVE_VALIDCA: "true"
    DONT_INIT_DATABASE: "true"
  script:
    - cd /var/www/s2low
    - vendor/bin/phpcs

phpstan:
  stage: static-analysis
  image : "$CONTAINER_IMAGE"
  variables:
    DONT_INIT_DATABASE: "true"
    DONT_RETRIEVE_VALIDCA: "true"
  script:
    - cd /var/www/s2low
    - vendor/bin/phpstan

unit_test:
    stage: test
    image : "$CONTAINER_IMAGE"
    services:
        - name: registry.libriciel.fr/public/outils/postgres:14.5
          alias: postgres
          command: ["postgres","-c", "max_connections=200"]
    variables:
        XDEBUG_ON: "true"
        POSTGRES_USER_TEST: s2lowuser
        POSTGRES_PASSWORD_TEST: s2lowpassword
        POSTGRES_DB_TEST: s2lowdb
        POSTGRES_DATABASE_TEST: s2lowdb
        POSTGRES_HOST_TEST: postgres
        POSTGRES_HOST: postgres
        DATABASE_URL: "postgresql://s2lowuser:s2lowpassword@postgres:5432/s2lowdb?serverVersion=14&charset=utf8"
        S2LOW_WEBSITE: "localhost"
        COMPOSER_PROCESS_TIMEOUT: 9000
        DONT_RETRIEVE_VALIDCA: "true"
        XDEBUG_MODE: coverage
        APP_ENV: test
        MAILER_DSN: smtp://mailsec:25?verify_peer=0
    script:
        - cd /var/www/s2low/
        - composer test-cover
        - cp -rf coverage $CI_PROJECT_DIR
    coverage: '/^\s*Lines:\s*\d+.\d+\%/'
    artifacts:
      paths:
        - coverage
      expire_in: 1h

code_quality:
  services:
  tags:
    - cq-sans-dind

container_scanning:
  variables:
    CS_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH

quality:
  stage: quality
  only:
    - master
  image:
    name: hubdocker.libriciel.fr/sonarsource/sonar-scanner-cli:11.5@sha256:46341f2c2dc560381414e90347885f5cddc716db080adcbafc1cac13e1473094
    entrypoint: [ "/bin/sh", "-c" ]
  script:
    - sonar-scanner -Dsonar.token=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST_URL

security-check:
  allow_failure: true
  before_script:
    - cp .trivyignore /

publish-container-to-registry:
  before_script:
    - date=$(date)
    - sed -i "s/%CI_BUILD_ID%/${CI_PIPELINE_ID}/" ./manifest.txt
    - sed -i "s/%BUILD_DATE%/$date/" ./manifest.txt
    - sed -i "s/%VERSION%/${CI_COMMIT_REF_NAME}/" ./manifest.txt

generate-sbom-compose:
  needs: [ "publish-container-to-registry"]

package-sbom-compose:
  needs: [ "generate-sbom-compose" ]

publish-compose:
  needs: [ "publish-container-to-registry", "package-sbom-compose" ]
  variables:
    INPUT_DIRECTORY: ./
  before_script:
    - mv docker-resources docker-resources-orig
    - mkdir docker-resources
    - mv docker-resources-orig/Makefile docker-resources/
    - sed -i "s/canary$/${CI_COMMIT_REF_NAME}/" ./docker-compose.yml

deploy_app:
  stage: staging
  only:
    - master
  variables:
    PAYLOAD: "payload={\"text\": \"[s2low-5-0.dev.libriciel.net](https://s2low-5-0.dev.libriciel.net) a été mis à jour - [build $CI_PIPELINE_ID]($CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID)\"}"
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - scp ./docker-compose.yml s2low@s2low-5-0.dev.libriciel.net:/opt/s2low/
    - scp ./docker-compose.test.yml s2low@s2low-5-0.dev.libriciel.net:/opt/s2low/docker-compose.override.yml
    - echo "$DEV_ENV_FILE" > /tmp/.env
    - scp /tmp/.env s2low@s2low-5-0.dev.libriciel.net:/opt/s2low/
    - ssh -tt s2low@s2low-5-0.dev.libriciel.net "cd /opt/s2low/ && docker compose pull && docker compose up -d"
    - curl -i -X POST -d "$PAYLOAD" $MATTERMOST_WEBHOOK
