version: '3.5'

services:
    web:
        image: s2low-local-dev
        build:
            context: .
            target: s2low_dev
        networks:
          - dgcl
          - dgfip
          - services
        ports:
            - "${WEB_HTTP_PORT}:80"
            - "${WEB_HTTPS_PORT}:443"
        volumes:
            - .:/var/www/s2low
        environment:
            POSTGRES_HOST_TEST: ${POSTGRES_HOST_TEST}
            POSTGRES_USER_TEST: ${POSTGRES_USER_TEST}
            POSTGRES_PASSWORD_TEST: ${POSTGRES_PASSWORD_TEST}
            POSTGRES_DATABASE_TEST: ${POSTGRES_DATABASE_TEST}
            WEB_HTTP_PORT: ${WEB_HTTP_PORT}
            WEB_HTTPS_PORT: ${WEB_HTTPS_PORT}
            ACTES_ALWAYS_CAN_VALIDATE: "true"
            XDEBUG_ON: ${XDEBUG_ON}
            XDEBUG_MODE: "coverage"

    db:
        environment:
            - POSTGRES_LOG_ALL_QUERY_TO_STDOUT=true


    db_test:
        image: gitlab.libriciel.fr:4567/docker/postgres:9.6.5
        networks:
          - services
        environment:
            - POSTGRES_USER=${POSTGRES_USER_TEST}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST}
            - POSTGRES_DB=${POSTGRES_DATABASE_TEST}
        volumes:
            - ${POSTGRESQL_DATADIR_TEST}:/var/lib/postgresql/data

    phppgadmin:
        image: keepitcool/phppgadmin
        networks:
          - services
        environment:
            - DB_HOST=db
            - DB_PORT=5432
        links:
            - db:db
        ports:
            - "${PHPPGADMIN_HTTP_PORT}:80"

    beanstalkd-console:
        image: schickling/beanstalkd-console
        networks:
            - services
        ports:
            - ${BEANSTALKD_CONSOLE_PORT}:2080
        links:
            - beanstalkd:beanstalkd

    php-redis-admin:
        image: faktiva/php-redis-admin
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        ports:
            - "${PHP_REDIS_PORT:-8005}:80"
        depends_on:
            - redis
        networks:
            - services

    maildev:
        image: maildev/maildev
        networks:
            - services
        ports:
            - 1080:80
