name: s2low

services:
    web:
        restart: unless-stopped
        image: registry.libriciel.fr/public/plateforme/s2low:canary
        networks:
          - openstack
          - dgcl
          - dgfip
          - services
        ports:
            - "${WEB_HTTP_PORT:-18080}:8080"
            - "${WEB_HTTPS_PORT:-10443}:8443"
        read_only: true
        environment:
            EMAIL_ADMIN_TECHNIQUE: ${EMAIL_ADMIN_TECHNIQUE:-noreply@libriciel.net}
            S2LOW_WEBSITE: ${S2LOW_WEBSITE:-localhost}
            S2LOW_WEBSITE_MAIL: ${S2LOW_WEBSITE_MAIL:-localhost}
            WEB_HTTP_PORT: ${WEB_HTTP_PORT:-18080}
            WEB_HTTPS_PORT: ${WEB_HTTPS_PORT:-10443}
            S2LOW_USE_STAPLING: ${S2LOW_USE_STAPLING:-off}
            S2LOW_STAPLING_RESPONDER_ERRORS: ${S2LOW_STAPLING_RESPONDER_ERRORS:-off}
            MAIL_USE_STAPLING: ${MAIL_USE_STAPLING:-off}
            MAIL_STAPLING_RESPONDER_ERRORS: ${MAIL_STAPLING_RESPONDER_ERRORS:-off}
            OPERATEUR_DE_TELETRANSMISSION: ${OPERATEUR_DE_TELETRANSMISSION:-LIBRICIEL}
            POSTGRES_USER: ${POSTGRES_USER:-s2lowuserpg}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-s2lowpwdpg}
            POSTGRES_DB: ${POSTGRES_DB:-s2lowdb}
            POSTGRES_HOST: ${POSTGRES_HOST:-db}
            CONVERT_API_LOGINS_FROM_ISO: ${CONVERT_API_LOGINS_FROM_ISO:-false}
            HELIOS_FTP_P_APPLI: ${HELIOS_FTP_P_APPLI:-GHELPES2}
            HELIOS_NB_FILES_ENVOI: ${HELIOS_NB_FILES_ENVOI:-1}
            HELIOS_SENDING_DESTINATION: ${HELIOS_SENDING_DESTINATION:-/entree/}
            HELIOS_USE_PASSTRANS_AS_DEFAULT: true
            HELIOS_FTP_SERVER: ${HELIOS_FTP_SERVER:-ftp}
            HELIOS_FTP_PORT: ${HELIOS_FTP_PORT:-21}
            HELIOS_FTP_PASSIVE_MODE: ${HELIOS_FTP_PASSIVE_MODE:-true}
            HELIOS_FTP_CONNECTION_MODE: ${HELIOS_FTP_CONNECTION_MODE:-SIMULATEUR}
            HELIOS_FTP_LOGIN: ${HELIOS_FTP_LOGIN:-helios}
            HELIOS_FTP_PASSWORD: ${HELIOS_FTP_PASSWORD:-helios}
            HELIOS_FTP_RESPONSE_SERVER_PATH: ${HELIOS_FTP_RESPONSE_SERVER_PATH:-/sortie/}
            HELIOS_PASSTRANS_RECEPTION_ENABLE: ${HELIOS_PASSTRANS_RECEPTION_ENABLE:-false}
            HELIOS_NB_FILES_ENVOI_PASSTRANS: ${HELIOS_NB_FILES_ENVOI_PASSTRANS:-1}
            HELIOS_PASSTRANS_SERVER: ${HELIOS_PASSTRANS_SERVER:-ftp_passtrans}
            HELIOS_PASSTRANS_PORT: ${HELIOS_PASSTRANS_PORT:-21}
            HELIOS_PASSTRANS_PASSIVE_MODE: ${HELIOS_PASSTRANS_PASSIVE_MODE:-true}
            HELIOS_PASSTRANS_CONNECTION_MODE: ${HELIOS_PASSTRANS_CONNECTION_MODE:-SIMULATEUR}
            HELIOS_PASSTRANS_LOGIN: ${HELIOS_PASSTRANS_LOGIN:-helios-passtrans}
            HELIOS_PASSTRANS_PASSWORD: ${HELIOS_PASSTRANS_PASSWORD:-helios-passtrans}
            HELIOS_PASSTRANS_SENDING_DESTINATION: ${HELIOS_PASSTRANS_SENDING_DESTINATION:-/entree/}
            HELIOS_PASSTRANS_RESPONSE_SERVER_PATH: ${HELIOS_PASSTRANS_RESPONSE_SERVER_PATH:-/sortie/}
            MAILER_DSN: ${MAILER_DSN:-smtp://mailsec:25?verify_peer=0}
            TDT_FROM_EMAIL: ${TDT_FROM_EMAIL:-Tiers de télétransmission <s2low@s2low.docker.libriciel.fr>}
            PUBLISH_SIMULATEUR: ${PUBLISH_SIMULATEUR:-true}
            MAIL_MESSAGE: ${MAIL_MESSAGE:-}
            MAIL_TEXT: ${MAIL_TEXT:-}
            ONLY_USE_VALIDCARGS: ${ONLY_USE_VALIDCARGS:-false}

            OPENSTACK_ENABLE: ${OPENSTACK_ENABLE:-false}
            ACTES_OPENSTACK_AUTHENTICATION_URL_V3: ${ACTES_OPENSTACK_AUTHENTICATION_URL_V3:-}
            ACTES_OPENSTACK_USERNAME: ${ACTES_OPENSTACK_USERNAME:-}
            ACTES_OPENSTACK_PASSWORD: ${ACTES_OPENSTACK_PASSWORD:-}
            ACTES_OPENSTACK_TENANT: ${ACTES_OPENSTACK_TENANT:-}
            ACTES_OPENSTACK_REGION: ${ACTES_OPENSTACK_REGION:-}
            ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            HELIOS_OPENSTACK_AUTHENTICATION_URL_V3: ${HELIOS_OPENSTACK_AUTHENTICATION_URL_V3:-}
            HELIOS_OPENSTACK_USERNAME: ${HELIOS_OPENSTACK_USERNAME:-}
            HELIOS_OPENSTACK_PASSWORD: ${HELIOS_OPENSTACK_PASSWORD:-}
            HELIOS_OPENSTACK_TENANT: ${HELIOS_OPENSTACK_TENANT:-}
            HELIOS_OPENSTACK_REGION: ${HELIOS_OPENSTACK_REGION:-}
            HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3: ${HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3:-}
            HELIOS_ACQUIT_OPENSTACK_USERNAME: ${HELIOS_ACQUIT_OPENSTACK_USERNAME:-}
            HELIOS_ACQUIT_OPENSTACK_PASSWORD: ${HELIOS_ACQUIT_OPENSTACK_PASSWORD:-}
            HELIOS_ACQUIT_OPENSTACK_TENANT: ${HELIOS_ACQUIT_OPENSTACK_TENANT:-}
            HELIOS_ACQUIT_OPENSTACK_REGION: ${HELIOS_ACQUIT_OPENSTACK_REGION:-}
            HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3: ${HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3:-}
            HELIOS_RETOUR_OPENSTACK_USERNAME: ${HELIOS_RETOUR_OPENSTACK_USERNAME:-}
            HELIOS_RETOUR_OPENSTACK_PASSWORD: ${HELIOS_RETOUR_OPENSTACK_PASSWORD:-}
            HELIOS_RETOUR_OPENSTACK_TENANT: ${HELIOS_RETOUR_OPENSTACK_TENANT:-}
            HELIOS_RETOUR_OPENSTACK_REGION: ${HELIOS_RETOUR_OPENSTACK_REGION:-}
            HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            MAILSEC_OPENSTACK_AUTHENTICATION_URL_V3: ${HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3:-}
            MAILSEC_OPENSTACK_USERNAME: ${HELIOS_ACQUIT_OPENSTACK_USERNAME:-}
            MAILSEC_OPENSTACK_PASSWORD: ${HELIOS_ACQUIT_OPENSTACK_PASSWORD:-}
            MAILSEC_OPENSTACK_TENANT: ${HELIOS_ACQUIT_OPENSTACK_TENANT:-}
            MAILSEC_OPENSTACK_REGION: ${HELIOS_ACQUIT_OPENSTACK_REGION:-}
            MAILSEC_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            CLOUD_PROVIDER_ENDPOINT: ${CLOUD_PROVIDER_ENDPOINT:-}
            CLOUD_PROVIDER_KEY: ${CLOUD_PROVIDER_KEY:-}
            CLOUD_PROVIDER_SECRET: ${CLOUD_PROVIDER_SECRET:-}
            CLOUD_BUCKET_ACTE_ENVELOPPE: ${CLOUD_BUCKET_ACTE_ENVELOPPE:-}
            CLOUD_BUCKET_PES_ALLER: ${CLOUD_BUCKET_PES_ALLER:-}
            CLOUD_BUCKET_PES_ACQUIT: ${CLOUD_BUCKET_PES_ACQUIT:-}
            CLOUD_BUCKET_PES_RETOUR: ${CLOUD_BUCKET_PES_RETOUR:-}
            CLOUD_BUCKET_MAIL_SEC: ${CLOUD_BUCKET_MAIL_SEC:-}

            ACTES_TDT_MAIL_ADDRESS: ${ACTES_TDT_MAIL_ADDRESS:-mail@s2low.docker.libriciel.net}
            ACTES_IMAP_LOGIN: ${ACTES_IMAP_LOGIN:-mail@s2low.docker.libriciel.net}
            ACTES_IMAP_PASSWORD: ${ACTES_IMAP_PASSWORD:-password}
            ACTES_IMAP_HOST: ${ACTES_IMAP_HOST:-mail}
            ACTES_IMAP_PORT: ${ACTES_IMAP_PORT:-143}
            ACTES_IMAP_OPTIONS: ${ACTES_IMAP_OPTIONS:-/imap/notls/novalidate-cert}

            ACTES_MINISTERE_URL: ${ACTES_MINISTERE_URL:-http://simulateur/Simulateur/actesPost}
            ACTES_MINISTERE_AUTHENTICATION: ${ACTES_MINISTERE_AUTHENTICATION:-NONE}
            ACTES_MINISTERE_LOGIN: ${ACTES_MINISTERE_LOGIN:-}
            ACTES_MINISTERE_PASSWORD: ${ACTES_MINISTERE_PASSWORD:-}
            ACTES_MINISTERE_CERTIFICATE: ${ACTES_MINISTERE_CERTIFICATE:-}
            ACTES_MINISTERE_CERTIFICATE_KEY: ${ACTES_MINISTERE_CERTIFICATE_KEY:-}
            ACTES_MINISTERE_CERTIFICATE_KEY_PASS: ${ACTES_MINISTERE_CERTIFICATE_KEY_PASS:-}
            ACTES_MINISTERE_SERVER_CERTIFICATE_PATH: ${ACTES_MINISTERE_SERVER_CERTIFICATE_PATH:-}
            ACTES_MINISTERE_ADAPT_PROTOCOL: ${ACTES_MINISTERE_ADAPT_PROTOCOL:-false}
            ACTES_MINISTERE_USE_LEGACY_PROTOCOL: ${ACTES_MINISTERE_USE_LEGACY_PROTOCOL:-true}

            ACTES_APPLI_NAME: ${ACTES_APPLI_NAME:-TACT}
            ACTES_APPLI_TRIGRAMME: ${ACTES_APPLI_TRIGRAMME:-abc}
            ACTES_APPLI_QUADRIGRAMME: ${ACTES_APPLI_QUADRIGRAMME:-TACT}
            ACTES_MAIL_BACKUP: ${ACTES_MAIL_BACKUP:-}

            ACTES_COMMON_BROADCAST_EMAILS: ${ACTES_COMMON_BROADCAST_EMAILS:-}

            USE_LEGACY_BORDEREAU_MODEL: ${USE_LEGACY_BORDEREAU_MODEL-false}
            USE_LEGACY_SECURE_MAIL_FIELDS: ${USE_LEGACY_SECURE_MAIL_FIELDS-false}
            MAIL_TEDETIS_FROM: ${MAIL_TEDETIS_FROM-}
            MAIL_SECURE_DESCRIPTION: ${MAIL_SECURE_DESCRIPTION-}

            LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN:-}
            LETSENCRYPT_SUB_DOMAIN: ${LETSENCRYPT_SUB_DOMAIN:-}
            LETSENCRYPT_MAILSEC_DOMAIN: ${LETSENCRYPT_MAILSEC_DOMAIN:-}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-}

            ACME_APP_ENABLED: ${ACME_APP_ENABLED:-false}
            ACME_APP_SERVER: ${ACME_APP_SERVER:-}
            ACME_APP_EMAIL: ${ACME_APP_EMAIL:-${LETSENCRYPT_EMAIL:-}}
            ACME_APP_DOMAIN: ${ACME_APP_DOMAIN:-${LETSENCRYPT_DOMAIN:-}}
            ACME_APP_ADDITIONAL_DOMAINS: ${ACME_APP_ADDITIONAL_DOMAINS:-${LETSENCRYPT_SUB_DOMAIN:-}}
            ACME_APP_RENEW_BEFORE_DAYS: ${ACME_APP_RENEW_BEFORE_DAYS:-30}
            ACME_APP_KEY_SIZE: ${ACME_APP_KEY_SIZE:-4096}
            ACME_APP_EAB_KID: ${ACME_APP_EAB_KID:-}
            ACME_APP_EAB_HMAC_KEY: ${ACME_APP_EAB_HMAC_KEY:-}
            ACME_APP_DEST: ${ACME_APP_DEST:-/etc/apache2/ssl/app}

            ACME_MAILSEC_ENABLED: ${ACME_MAILSEC_ENABLED:-false}
            ACME_MAILSEC_SERVER: ${ACME_MAILSEC_SERVER:-}
            ACME_MAILSEC_EMAIL: ${ACME_MAILSEC_EMAIL:-${LETSENCRYPT_EMAIL:-}}
            ACME_MAILSEC_DOMAIN: ${ACME_MAILSEC_DOMAIN:-${LETSENCRYPT_MAILSEC_DOMAIN:-}}
            ACME_MAILSEC_RENEW_BEFORE_DAYS: ${ACME_MAILSEC_RENEW_BEFORE_DAYS:-30}
            ACME_MAILSEC_KEY_SIZE: ${ACME_MAILSEC_KEY_SIZE:-4096}
            ACME_MAILSEC_EAB_KID: ${ACME_MAILSEC_EAB_KID:-}
            ACME_MAILSEC_EAB_HMAC_KEY: ${ACME_MAILSEC_EAB_HMAC_KEY:-}
            ACME_MAILSEC_DEST: ${ACME_MAILSEC_DEST:-/etc/apache2/ssl/mailsec}

            ACTES_ALWAYS_CAN_VALIDATE: ${ACTES_ALWAYS_CAN_VALIDATE:-false}

            APP_ENV: ${APP_ENV:-prod}
            APP_DEBUG: ${APP_DEBUG:-false}
            USE_PROD_NOTIFICATIONS: ${USE_PROD_NOTIFICATIONS:-true}

            HELIOS_PURGE_ENABLE: ${HELIOS_PURGE_ENABLE:-false}
            HELIOS_RETENTION_FICHIERS_NB_JOURS: ${HELIOS_RETENTION_FICHIERS_NB_JOURS:-3650000}
            CIPHER_SUITE: ${CIPHER_SUITE:-ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305}
            SSL_PROTOCOL: ${SSL_PROTOCOL:--all -TLSv1.3 +TLSv1.2}
            SSL_INSECURE_RENEGOTIATION: ${SSL_INSECURE_RENEGOTIATION:-on}
            APACHE_LOG_LEVEL: ${APACHE_LOG_LEVEL:-info}
            WEBMASTER: ${WEBMASTER:-${S2LOW_WEBSITE:-mailto:webmaster@s2low.docker.libriciel.fr}}
        volumes:
            - ${WORKSPACE_VOLUME:-app_workspace}:/data/tdt-workspace
            - ${LOG_PATH:-app_logs}:/data/log/
            - ${SERVER_SSL_CERTIFICAT:-app_certificate}:/etc/apache2/ssl/
            - ${TIMESTAMP_CERTIFICAT_PATH:-app_certificate_timestamp}:/etc/s2low/ssl/
            - ${GENERAL_TRUST_STORE:-general_trust_store}:/data/certificate/truststore/
            - ${ACME_DATADIR:-${LETSENCRYPT_DATADIR:-letsencrypt_datadir}}:/etc/letsencrypt
        tmpfs:
            - /var/run:mode=770,uid=${UID:-33},gid=${GID:-33},size=10M
            - /data/config:mode=770,uid=${UID:-33},gid=${GID:-33},size=5M
            - /etc/apache2/sites-enabled:mode=770,uid=${UID:-33},gid=${GID:-33},size=5M
            - /var/lib/apache2/site/enabled_by_admin:mode=770,uid=${UID:-33},gid=${GID:-33},size=5M
            - /tmp:mode=770,uid=${UID:-33},gid=${GID:-33},size=8G
            - /data/run:mode=770,uid=${UID:-33},gid=${GID:-33},size=10M
            - /data/lock:mode=770,uid=${UID:-33},gid=${GID:-33},size=10M
            - /var/www/s2low/ext/standalone:mode=770,uid=${UID:-33},gid=${GID:-33},size=500M
            - /var/www/s2low/var/cache:mode=770,uid=${UID:-33},gid=${GID:-33},size=500M
            - /var/www/s2low/var/log:mode=770,uid=${UID:-33},gid=${GID:-33},size=500M
            - /var/www/parapheur/libersign:mode=770,uid=${UID:-33},gid=${GID:-33},size=500M
            - /acme-challenge/.well-known/acme-challenge:mode=770,uid=${UID:-33},gid=${GID:-33},size=10M
        user: "${UID:-33}:${GID:-33}"

    clamav:
        restart: unless-stopped
        image: hubdocker.libriciel.fr/clamav/clamav:0.105@sha256:f3d1d4aec64b1e3e2b714f8778dab16f0bf2f6a2e348873e0f7f85082a0d8a23
        networks:
          - services

    pades-valid:
        restart: unless-stopped
        image: registry.libriciel.fr/public/signature/pades-valid:1.4.10@sha256:e63795261768cbf7cd39f543fcea0c9efce9b6961f39536604ef16c40e69abcb

        networks:
          - services
        environment:
            JAVA_OPTS: "-Xmx512M"
        mem_limit: 768M

    pdf-stamp:
        restart: unless-stopped
        image: registry.libriciel.fr/public/signature/pdf-stamp:2.7.15@sha256:e111a2b77e67415270b0e9c149d4c7b5460aa464d379b390e15d27292576e261
        networks:
          - services
        mem_limit: 2G

    redis:
        restart: unless-stopped
        image: hubdocker.libriciel.fr/redis:8.6.0-alpine3.23@sha256:fd83658b0e40e2164617d262f13c02ca9ee9e1e6b276fd2fa06617e09bd5c780
        volumes:
            - ${REDIS_VOLUME:-redis_datadir}:/data
        command: redis-server --appendonly yes
        networks:
            - services

    beanstalkd:
        restart: unless-stopped
        image: hubdocker.libriciel.fr/schickling/beanstalkd:latest@sha256:19a928e3563973219e44f6c29df2a71103c7db894692ae94b7d0760837877e73
        networks:
            - services
networks:
  dgcl:
  dgfip:
  services:
  openstack:

volumes:
    db_datadir:
    app_workspace:
    app_certificate:
    app_certificate_timestamp:
    app_session:
    letsencrypt_datadir:
    app_logs:
    redis_datadir:
    general_trust_store:
