version: '3.5'

services:
    web:
        image: gitlab.libriciel.fr:4567/s2low/s2low:master
        networks:
          - dgcl
          - dgfip
          - services
        ports:
            - "80:80"
            - "443:443"
        environment:
            LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            POSTGRES_HOST_TEST: ${POSTGRES_HOST_TEST}
            POSTGRES_USER_TEST: ${POSTGRES_USER_TEST}
            POSTGRES_PASSWORD_TEST: ${POSTGRES_PASSWORD_TEST}
            POSTGRES_DATABASE_TEST: ${POSTGRES_DATABASE_TEST}
        volumes:
            - ${LETSENCRYPT_DATADIR}:/etc/letsencrypt
