services:
    web:
        image: s2low-local-dev
        build:
            context: .
            target: s2low_dev
            args:
                UID: ${UID:-33}
                GID: ${GID:-33}
                USERNAME: ${USER_NAME:-www-data} #USERNAME est en général dans l'environnement pris avant le .env
                GROUPNAME: ${GROUPNAME:-www-data}

        volumes:
            - .:/var/www/s2low
            - /data/s2low-dev/coverage/:/opt/phpstorm-coverage
        environment:
            POSTGRES_HOST_TEST: ${POSTGRES_HOST_TEST:-db_test}
            POSTGRES_USER_TEST: ${POSTGRES_USER_TEST:-dbusertest}
            POSTGRES_PASSWORD_TEST: ${POSTGRES_PASSWORD_TEST:-dbpasswordtest}
            POSTGRES_DATABASE_TEST: ${POSTGRES_DATABASE_TEST:-s2lowtest}
            CLOUD_PROVIDER_ENDPOINT: ${CLOUD_PROVIDER_ENDPOINT:-http://local-s3:9000}
            CLOUD_PROVIDER_KEY: ${CLOUD_PROVIDER_KEY:-admin}
            CLOUD_PROVIDER_SECRET: ${CLOUD_PROVIDER_SECRET:-password}

            XDEBUG_ON: ${XDEBUG_ON:-true}
            XDEBUG_MODE: "coverage"
            APP_ENV: ${APP_ENV:-dev}
            APP_DEBUG: ${APP_DEBUG:-true}
            USE_PROD_NOTIFICATIONS: ${USE_PROD_NOTIFICATIONS:-false}
        networks:
            - s3

    local-s3:
        image: minio/minio:RELEASE.2025-07-23T15-54-02Z-cpuv1@sha256:7330be2e7320a7a699b36f72bd06a94d8a21ec9f6f397345d9c38fc6751141f5
        ports:
            - '9000:9000' # acces API
            - '9001:9001' # console web
        environment:
            MINIO_ROOT_USER: 'admin'
            MINIO_ROOT_PASSWORD: 'password'
        command: server /data --console-address ":9001"
        volumes:
            - minio_data:/data
        networks:
            - s3

    db:
        environment:
            - POSTGRES_LOG_ALL_QUERY_TO_STDOUT=true
        ports:
            - '5432:5432'

    simulateur:
        ports:
            - ${SIMULATEUR_SITE_PORT:-10445}:80

    ftp:
        ports:
            - "${FTP_PORT:-10021}:21"
            - "${PASV_MIN_PORT:-65000}-${PASV_MAX_PORT:-65004}:${PASV_MIN_PORT:-65000}-${PASV_MAX_PORT:-65004}"

    db_test:
        restart: unless-stopped
        image: registry.libriciel.fr/public/outils/postgres:14.5@sha256:a0c6930be56082d2b6f747630ab6e5799c566c7ec45c49033e8b647ca2e50bee
        command: ["postgres","-c", "max_connections=200"]
        networks:
          - services
        environment:
            - POSTGRES_USER=${POSTGRES_USER_TEST:-dbusertest}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_TEST:-dbpasswordtest}
            - POSTGRES_DB=${POSTGRES_DATABASE_TEST:-s2lowtest}
        volumes:
            - ${POSTGRESQL_DATADIR_TEST:-db_datadir_test}:/var/lib/postgresql/data
        ports:
            - 15432:5432

    phppgadmin:
        restart: unless-stopped
        image: hubdocker.libriciel.fr/keepitcool/phppgadmin:5.1@sha256:c7b27011ca7a7b07a59cbb6baeb8922c068c7a2f171fe92452f6026489ddd018
        networks:
          - services
        environment:
            - DB_HOST=db
            - DB_PORT=5432
        links:
            - db:db
        ports:
            - "${PHPPGADMIN_HTTP_PORT:-10001}:80"

    beanstalkd-console:
        restart: unless-stopped
        image: hubdocker.libriciel.fr/schickling/beanstalkd-console:latest@sha256:950c8120986b536f1cdc431e28c8b7d6e5bada2a038a6fb5119d32323d41a76f
        networks:
            - services
        ports:
            - ${BEANSTALKD_CONSOLE_PORT:-10002}:2080
        links:
            - beanstalkd:beanstalkd

    php-redis-admin:
        restart: unless-stopped
        image: hubdocker.libriciel.fr/faktiva/php-redis-admin:latest@sha256:e7586bd4856fd462290cd1510110eacfd9edbc1944591e4d608e5ef804b302ee
        environment:
            - PHPREDMIN_DATABASE_REDIS_0_HOST=redis
        ports:
            - "${PHP_REDIS_PORT:-8005}:80"
        depends_on:
            - redis
        networks:
            - services

    maildev:
        restart: unless-stopped
        image: hubdocker.libriciel.fr/maildev/maildev:2.2.1@sha256:180ef51f65eefebb0e7122d8308813c1fd7bff164bc440ce5a3c2feee167a810
        networks:
            - services
        ports:
            - 1080:1080

    webpack:
        build:
            context: ./docker-resources/node/
        working_dir: /usr/app
        volumes:
            - .:/usr/app/

networks:
    s3:
volumes:
    db_datadir_test:
    openstack_datadir:
    minio_data:
