version: '2.0'

services:
    web:
        image: gitlab.libriciel.fr:4567/s2low/s2low:master
        links:
            - simulateur
            - ftp:ftp
        ports:
            - "80:80"
            - "443:443"
        environment:
            LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
            POSTGRES_HOST_TEST: ${POSTGRES_HOST_TEST}
            POSTGRES_USER_TEST: ${POSTGRES_USER_TEST}
            POSTGRES_PASSWORD_TEST: ${POSTGRES_PASSWORD_TEST}
            POSTGRES_DATABASE_TEST: ${POSTGRES_DATABASE_TEST}
        volumes:
            - ${LETSENCRYPT_DATADIR}:/etc/letsencrypt

    simulateur:
        image: gitlab.libriciel.fr:4567/s2low/simulateur-helios:master
        links:
             - ftp:ftp
             - mail:mail
        environment:
            SITE_INDEX: ${SIMULATEUR_SITE_INDEX}
        ports:
            - ${SIMULATEUR_SITE_PORT}:80
        volumes:
            - ${SIMULATEUR_WORKSPACE_DIRECTORY}:/var/www/simulateur-helios/workspace
        environment:
            MAIL_HOST: mail
            MAIL_PORT: 25
            MAIL_FROM: mail@tedetis.org

    ftp:
        image: mcreations/ftp
        environment:
            FTP_USER: ${HELIOS_FTP_LOGIN}
            FTP_PASS: ${HELIOS_FTP_PASSWORD}
            PASV_MIN_PORT: ${PASV_MIN_PORT}
            PASV_MAX_PORT: ${PASV_MAX_PORT}
        volumes:
          - ${SIMULATEUR_WORKSPACE_DIRECTORY}:/data/${HELIOS_FTP_LOGIN}/

    mail:
        build:
            context: ./docker-resources/
            dockerfile: Dockerfile-mail
        environment:
            - MAILNAME=tedetis.org
            - MAIL_ADDRESS=mail@tedetis.org
            - MAIL_PASS=password

