version: '3.7'

services:
    web:
        image: registry.libriciel.fr:443/public/plateforme/s2low:canary
        networks:
          - openstack
          - dgcl
          - dgfip
          - services
        ports:
            - "${WEB_HTTP_PORT:-10080}:80"
            - "${WEB_HTTPS_PORT:-10443}:443"
        read_only: true
        environment:
            EMAIL_ADMIN_TECHNIQUE: ${EMAIL_ADMIN_TECHNIQUE:-test@libriciel.net}
            S2LOW_WEBSITE: ${S2LOW_WEBSITE:-localhost}
            POSTGRES_USER: ${POSTGRES_USER:-tedetis}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tedetis}
            POSTGRES_DB: ${POSTGRES_DB:-tedetis}
            POSTGRES_HOST: ${POSTGRES_HOST:-}
            HELIOS_FTP_SERVER: ${HELIOS_FTP_SERVER:-ftp}
            HELIOS_FTP_PORT: ${HELIOS_FTP_PORT:-21}
            HELIOS_FTP_PASSIVE_MODE: ${HELIOS_FTP_PASSIVE_MODE:-false}
            HELIOS_SENDING_MODE_DEMO: ${HELIOS_SENDING_MODE_DEMO:-true}
            HELIOS_FTP_PASSTRANS_MODE: ${HELIOS_FTP_PASSTRANS_MODE:-false}
            HELIOS_FTP_P_APPLI: ${HELIOS_FTP_P_APPLI:-THELPES2}
            HELIOS_FTP_LOGIN: ${HELIOS_FTP_LOGIN:-helios}
            HELIOS_FTP_PASSWORD: ${HELIOS_FTP_PASSWORD:-helios}
            HELIOS_SENDING_DESTINATION: ${HELIOS_SENDING_DESTINATION:-/entree/}
            HELIOS_FTP_RESPONSE_SERVER_PATH: ${HELIOS_FTP_RESPONSE_SERVER_PATH:-/sortie/}
            SMTP_SERVER: ${SMTP_SERVER:-mailsec}
            SMTP_PORT: ${SMTP_PORT:-25}
            MAILER_DSN: ${MAILER_DSN:-smtp://mailsec:25?verify_peer=0}
            PUBLISH_SIMULATEUR: ${PUBLISH_SIMULATEUR:-true}
            ACTES_OPENSTACK_AUTHENTICATION_URL_V3: ${ACTES_OPENSTACK_AUTHENTICATION_URL_V3:-}
            ACTES_OPENSTACK_USERNAME: ${ACTES_OPENSTACK_USERNAME:-}
            ACTES_OPENSTACK_PASSWORD: ${ACTES_OPENSTACK_PASSWORD:-}
            ACTES_OPENSTACK_TENANT: ${ACTES_OPENSTACK_TENANT:-}
            ACTES_OPENSTACK_REGION: ${ACTES_OPENSTACK_REGION:-}
            ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            HELIOS_OPENSTACK_AUTHENTICATION_URL_V3: ${HELIOS_OPENSTACK_AUTHENTICATION_URL_V3:-}
            HELIOS_OPENSTACK_USERNAME: ${HELIOS_OPENSTACK_USERNAME:-}
            HELIOS_OPENSTACK_PASSWORD: ${HELIOS_OPENSTACK_PASSWORD:-}
            HELIOS_OPENSTACK_TENANT: ${HELIOS_OPENSTACK_TENANT:-}
            HELIOS_OPENSTACK_REGION: ${HELIOS_OPENSTACK_REGION:-}
            HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3: ${HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3:-}
            HELIOS_ACQUIT_OPENSTACK_USERNAME: ${HELIOS_ACQUIT_OPENSTACK_USERNAME:-}
            HELIOS_ACQUIT_OPENSTACK_PASSWORD: ${HELIOS_ACQUIT_OPENSTACK_PASSWORD:-}
            HELIOS_ACQUIT_OPENSTACK_TENANT: ${HELIOS_ACQUIT_OPENSTACK_TENANT:-}
            HELIOS_ACQUIT_OPENSTACK_REGION: ${HELIOS_ACQUIT_OPENSTACK_REGION:-}
            HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3: ${HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3:-}
            HELIOS_RETOUR_OPENSTACK_USERNAME: ${HELIOS_RETOUR_OPENSTACK_USERNAME:-}
            HELIOS_RETOUR_OPENSTACK_PASSWORD: ${HELIOS_RETOUR_OPENSTACK_PASSWORD:-}
            HELIOS_RETOUR_OPENSTACK_TENANT: ${HELIOS_RETOUR_OPENSTACK_TENANT:-}
            HELIOS_RETOUR_OPENSTACK_REGION: ${HELIOS_RETOUR_OPENSTACK_REGION:-}
            HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            MAILSEC_OPENSTACK_AUTHENTICATION_URL_V3: ${HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3:-}
            MAILSEC_OPENSTACK_USERNAME: ${HELIOS_ACQUIT_OPENSTACK_USERNAME:-}
            MAILSEC_OPENSTACK_PASSWORD: ${HELIOS_ACQUIT_OPENSTACK_PASSWORD:-}
            MAILSEC_OPENSTACK_TENANT: ${HELIOS_ACQUIT_OPENSTACK_TENANT:-}
            MAILSEC_OPENSTACK_REGION: ${HELIOS_ACQUIT_OPENSTACK_REGION:-}
            MAILSEC_OPENSTACK_SWIFT_CONTAINER_PREFIX: ${HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX:-}

            ACTES_IMAP_LOGIN: ${ACTES_IMAP_LOGIN:-mail@tedetis.org}
            ACTES_IMAP_PASSWORD: ${ACTES_IMAP_PASSWORD:-password}
            MAILNAME: ${MAILNAME:-mail}

            USE_LEGACY_BORDEREAU_MODEL: ${USE_LEGACY_BORDEREAU_MODEL-false}
            USE_LEGACY_SECURE_MAIL_FIELDS: ${USE_LEGACY_SECURE_MAIL_FIELDS-true}

            LETSENCRYPT_DOMAIN: ${LETSENCRYPT_DOMAIN:-}
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-}

            ACTES_ALWAYS_CAN_VALIDATE: ${ACTES_ALWAYS_CAN_VALIDATE:-false}

            APP_ENV: prod

        volumes:
            - ${WORKSPACE_VOLUME:-app_workspace}:/data/tdt-workspace
            - ${SERVER_SSL_CERTIFICAT:-app_certificate}:/etc/apache2/ssl/
            - ${TIMESTAMP_CERTIFICAT_PATH:-app_certificate_timestamp}:/etc/s2low/ssl/
            - ${LOG_PATH:-app_logs}:/data/log/
            - ${LETSENCRYPT_DATADIR:-letsencrypt_datadir}:/etc/letsencrypt
            - ${GENERAL_TRUST_STORE:-general_trust_store}:/data/certificate/truststore/
        tmpfs:
            - /var/run:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /data/config:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /etc/apache2/sites-enabled:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /var/lib/apache2/site/enabled_by_admin:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /tmp:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /data/run:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /data/lock:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /var/www/s2low/ext/standalone:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /var/www/s2low/var/cache:mode=770,uid=${UID:-33},gid=${GID:-33}
            - /var/www/s2low/var/log:mode=770,uid=${UID:-33},gid=${GID:-33}
        user: "${UID:-33}:${GID:-33}"

    db:
        image: gitlab.libriciel.fr:4567/docker/postgres:9.6.5
        networks:
          - services
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-tedetis}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-tedetis}
            - POSTGRES_DB=${POSTGRES_DB:-tedetis}
        volumes:
            - ${POSTGRESQL_DATADIR:-db_datadir}:/var/lib/postgresql/data

    clamav:
        image: mkodockx/docker-clamav
        networks:
          - services

    pades-valid:
        image: gitlab.libriciel.fr:4567/outils/pades-valid:1.4.7
        networks:
          - services

    pdf-stamp:
        image: gitlab.libriciel.fr:4567/outils/pdf-stamp:2.4.5
        networks:
          - services

    redis:
        image: redis:3.2
        restart: always
        volumes:
            - ${REDIS_VOLUME:-redis_datadir}:/data
        command: redis-server --appendonly yes
        networks:
            - services

    beanstalkd:
        image: schickling/beanstalkd
        restart: always
        networks:
            - services
networks:
  dgcl:
  dgfip:
  services:
  openstack:

volumes:
    db_datadir:
    app_workspace:
    app_certificate:
    app_certificate_timestamp:
    app_session:
    letsencrypt_datadir:
    app_logs:
    redis_datadir:
    general_trust_store: