# For all environnements except production
version: '3.7'

services:
  simulateur:
    image: gitlab.libriciel.fr:4567/libriciel/pole-plate-formes/s2low/projets-annexes/simulateur-helios:1.1.2
    networks:
      - dgfip
      - dgcl
      - services
    depends_on:
      - ftp
    volumes:
      - ${SIMULATEUR_WORKSPACE_DIRECTORY:-ftp_datadir}:/var/www/simulateur-helios/workspace
    environment:
      MAIL_HOST: mail
      MAIL_PORT: 25
      MAIL_FROM: "dgcl@${MAILNAME:-mail}"

  ftp:
    image: mcreations/ftp
    networks:
      - dgfip
    environment:
      FTP_USER: ${HELIOS_FTP_LOGIN:-helios}
      FTP_PASS: ${HELIOS_FTP_PASSWORD:-helios}
      PASV_MIN_PORT: ${PASV_MIN_PORT:-65000}
      PASV_MAX_PORT: ${PASV_MAX_PORT:-65004}
    volumes:
      - ${SIMULATEUR_WORKSPACE_DIRECTORY:-ftp_datadir}:/data/${HELIOS_FTP_LOGIN:-helios}/

  mail:
    image: gitlab.libriciel.fr:4567/docker/docker-imap-devel:1.0
    networks:
      - services
    environment:
      - MAILNAME=${MAILNAME:-mail}
      - MAIL_ADDRESS=${ACTES_IMAP_LOGIN:-mail@tedetis.org}
      - MAIL_PASS=${ACTES_IMAP_PASSWORD:-password}

  mailsec:
    image: gitlab.libriciel.fr:4567/docker/mail-master:1.0
    networks:
      - services
    environment:
      - DOMAINS=${MAILNAME:-mail}
      - POSTFIX_HOSTNAME=s2low-mailsec.libriciel.fr
      - MAILS=${IMAP_LOGIN:-mail@tedetis.org}
      - NOPASS=true
volumes:
  ftp_datadir:
