version: '3.5'

services:
    web:
        image: gitlab.libriciel.fr:4567/s2low/s2low:4.1.0
        networks:
          - dgcl
          - dgfip
          - services
        environment:
            PUBLISH_SIMULATEUR: "true"
        ports:
          - 80:80
          - 443:443

    db:
        image: gitlab.libriciel.fr:4567/docker/postgres:9.6.5
        networks:
          - services
        environment:
            - POSTGRES_USER=s2lowuser
            - POSTGRES_PASSWORD=s2lowpassword
            - POSTGRES_DB=s2lowdb

    db_test:
        build:
            context: ./docker-resources/
            dockerfile: Dockerfile-postgres
        environment:
            - POSTGRES_USER=s2lowtestuser
            - POSTGRES_PASSWORD=s2lowtestpassword
            - POSTGRES_DB=s2lowdbtest
    clamav:
        image: mkodockx/docker-clamav
        networks:
          - services

    pades-valid:
        image: gitlab.libriciel.fr:4567/outils/pades-valid:1.1.1
        networks:
          - services

    pdf-stamp:
        image: gitlab.libriciel.fr:4567/outils/pdf-stamp:1.3.0
        networks:
          - services

    ftp:
        image: mcreations/ftp
        networks:
          - dgfip
        environment:
            FTP_USER: helios
            FTP_PASS: helios
            PASV_MIN_PORT: 65000
            PASV_MAX_PORT: 65004
        volumes:
          - dgfip:/data/helios/

    mail:
        image: gitlab.libriciel.fr:4567/docker/docker-imap-devel:1.0
        networks:
          - services
        environment:
            - MAILNAME=s2low.docker.libriciel.fr
            - MAIL_ADDRESS=s2low@s2low.docker.libriciel.fr
            - MAIL_PASS=password

    mailsec:
        image: gitlab.libriciel.fr:4567/docker/mail-master:1.0
        networks:
          - services
        environment:
            - DOMAINS=s2low.docker.libriciel.fr
            - POSTFIX_HOSTNAME=s2low-mailsec.docker.libriciel.fr
            - MAILS=s2low-mailsec@s2low.docker.libriciel.fr
            - NOPASS=true

    simulateur:
        image: gitlab.libriciel.fr:4567/s2low/simulateur-helios:1.1.1
        networks:
          - dgfip
          - dgcl
          - services
        depends_on:
          - ftp
        environment:
            MAIL_HOST: mail
            MAIL_PORT: 25
            MAIL_FROM: dgcl@s2low.docker.libriciel.fr
        volumes:
            - dgfip:/var/www/simulateur-helios/workspace

    redis:
      image: redis:3.2
      restart: always
      command: redis-server --appendonly yes
      networks:
        - services

    beanstalkd:
      image: schickling/beanstalkd
      restart: always
      networks:
        - services

networks:
  dgcl:
  dgfip:
  services:

volumes:
  dgfip:
