# Required metadata
sonar.projectKey=s2low
sonar.projectName=s2low
sonar.projectVersion=master

# Project paths
sonar.sources=.
sonar.projectBaseDir=.
sonar.exclusions=vendor/**,ext/**,test/**,tests/**,temp/**,coverage-reports/**,db/**,data-exemple/**,xsd/**

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Coverage files path
sonar.php.tests.reportPath=coverage/logfile.xml
sonar.php.coverage.reportPaths=coverage/coverage.xml