; TODO à modifier en fonction d'une variable d'environnement
session.save_handler = redis
session.save_path = "tcp://redis:6379"
; Session de 24 minutes
session.gc_maxlifetime=1440

openssl.capath=/data/certificate/truststore

session.cookie_secure=1
session.use_only_cookies=1
session.cookie_httponly=1