Protocols h2 http/1.1

# TLS Protocols
SSLProtocol ${SSL_PROTOCOL}
SSLOptions +StdEnvVars +OptRenegotiate +ExportCertData +LegacyDNStringFormat
SSLInsecureRenegotiation ${SSL_INSECURE_RENEGOTIATION}

# Cipher Suites (TLSv1.2 only, TLSv1.3 uses its own internal suite)
SSLCipherSuite ${CIPHER_SUITE}
SSLSessionCacheTimeout 1500
SSLHonorCipherOrder on
SSLCompression off

# OCSP Stapling
SSLUseStapling ${USE_STAPLING}
SSLStaplingCache "shmcb:logs/ssl_stapling(32768)"
SSLStaplingReturnResponderErrors ${STAPLING_RESPONDER_ERRORS}

# Reducing MIME type security risks
Header set X-Content-Type-Options "nosniff"
# HTTP Strict Transport Security (HSTS)
Header always set Strict-Transport-Security "max-age=16070400; includeSubDomains"
# Server software information
Header always unset X-Powered-By
ServerTokens Prod
ServerSignature Off
TraceEnable Off