
ProxyPass "/TedetisActes" http://tomcat:8080/TedetisActes
ProxyPassReverse "/TedetisActes" http://tomcat:8080/TedetisActes



ProxyPass "/Simulateur" http://simulateur/Simulateur
ProxyPassReverse "/Simulateur" http://simulateur/Simulateur
