ServerTokens Prod
ServerSignature Off
TraceEnable Off

# Reducing MIME type security risks
Header set X-Content-Type-Options "nosniff"


# Server software information
Header unset X-Powered-By

Header set Content-Security-Policy "frame-ancestors 'self';"
Header set Referrer-Policy: same-origin
Header set Permissions-Policy "accelerometer=(), geolocation=('self'), fullscreen=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), display-capture=('self')"

SSLStaplingCache "shmcb:logs/ssl_stapling(32768)"