<VirtualHost *:443>
  SSLEngine on
  # Configuration SSL côté serveur
  SSLCertificateFile /etc/apache2/ssl/__SITENAME__/apache2-__SITENAME__-cert.pem
  SSLCertificateKeyFile /etc/apache2/ssl/__SITENAME__/apache2-__SITENAME__-priv-key.pem

  # Configuration SSL authentification utilisateurs
  SSLCACertificatePath  /etc/tedetis/ssl/validca
  SSLCARevocationPath /etc/tedetis/ssl/validca
  SSLVerifyClient require
  SSLVerifyDepth 2

  SSLOptions +StdEnvVars
  SSLCipherSuite RSA:!SSLv2:!RC2:!DES:!EXP:!eNULL


  ServerAdmin webmaster@ntsys.fr
  ServerName __SITENAME__
  DocumentRoot /var/www/tedetis/public.ssl

  <Directory /var/www/tedetis/public.ssl>
        Options -Indexes
  </Directory>

  ErrorLog /var/log/apache2/__SITENAME__-ssl-error.log
  CustomLog /var/log/apache2/__SITENAME__-ssl-access.log combined
</VirtualHost>
