
[program:helios-store-pes-aller-in-cloud]
command=php /var/www/s2low/cron/helios-store-pes-aller-in-cloud.php
autorestart=true

[program:helios-menage]
command=php /var/www/s2low/cron/helios-menage.php
autorestart=true

[program:actes-store-envelope-in-cloud]
command=php /var/www/s2low/cron/actes-store-envelope-in-cloud.php
autorestart=true

[program:actes-menage-enveloppe]
command=php /var/www/s2low/cron/actes-menage-enveloppe.php
autorestart=true

[program:helios-menage-pes-acquit]
command=php /var/www/s2low/cron/helios-menage-pes-acquit.php
autorestart=true

[program:helios-store-pes-acquit-in-cloud]
command=php /var/www/s2low/cron/helios-store-pes-acquit-in-cloud.php
autorestart=true

[program:helios-menage-pes-retour]
command=php /var/www/s2low/cron/helios-menage-pes-retour.php
autorestart=true

[program:helios-store-pes-retour-in-cloud]
command=php /var/www/s2low/cron/helios-store-pes-retour-in-cloud.php
autorestart=true

[program:mailsec-store-files-in-cloud]
command=php /var/www/s2low/cron/mailsec-store-files-in-cloud.php
autorestart=true

[program:mailsec-menage]
command=php /var/www/s2low/cron/mailsec-menage.php
autorestart=true
