
[program:helios-store-pes-aller-in-cloud]
command=php /var/www/s2low/cron/helios-store-pes-aller-in-cloud.php
autorestart=true
user=www-data

[program:helios-delete-old-pes-aller.php]
command=php /var/www/s2low/cron/helios-delete-old-pes-aller.php 3600
autorestart=true
user=www-data