
[program:helios-store-pes-aller-in-cloud]
command=php /var/www/s2low/cron/helios-store-pes-aller-in-cloud.php
autorestart=true
user=www-data

[program:helios-menage]
command=php /var/www/s2low/cron/helios-menage.php
autorestart=true
user=www-data

[program:actes-store-envelope-in-cloud]
command=php /var/www/s2low/cron/actes-store-envelope-in-cloud.php
autorestart=true
user=www-data

[program:actes-grand-menage]
command=/bin/bash /var/www/s2low/docker-resources/cron-launcher/actes-grand-menage.sh
autorestart=true
user=www-data

[program:helios-menage-pes-acquit]
command=php /var/www/s2low/cron/helios-menage-pes-acquit.php
autorestart=true
user=www-data

[program:helios-store-pes-acquit-in-cloud]
command=php /var/www/s2low/cron/helios-store-pes-acquit-in-cloud.php
autorestart=true
user=www-data

[program:helios-menage-pes-retour]
command=php /var/www/s2low/cron/helios-menage-pes-retour.php
autorestart=true
user=www-data

[program:helios-store-pes-retour-in-cloud]
command=php /var/www/s2low/cron/helios-store-pes-retour-in-cloud.php
autorestart=true
user=www-data