
[program:cron]
command = /usr/sbin/cron -f -L 15
autostart = true
autorestart = true
stdout_logfile=/data/log/cron-stdout.log
stderr_logfile=/data/log/cron-stderr.log

[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && /usr/local/bin/wait-for-certificates.sh && exec /usr/sbin/apache2 -DFOREGROUND"
stdout_events_enabled=true
stderr_events_enabled=true
autorestart=true
stdout_logfile=/data/log/apache2-stdout.log
stderr_logfile=/data/log/apache2-stderr.log
