
# Ce script est utilise dans la procedure d'install, ne pas effacer...

[eventlistener:process-failed]
command=php /var/www/s2low/cron/process-failed.php
events=PROCESS_STATE_FATAL
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=unexpected
env=HOME="/var/www"
directory=/var/www

[program:actes-antivirus]
command=php /var/www/s2low/cron/actes-antivirus.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:actes-analyse-fichier-a-envoyer]
command=php /var/www/s2low/cron/actes-analyse-fichier-a-envoyer.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:actes-envoi-fichier]
command=php /var/www/s2low/cron/actes-envoi-fichier.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:actes-envoi-ar]
command=php /var/www/s2low/cron/actes-envoi-ar.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:actes-reception-fichier]
command=php /var/www/s2low/cron/actes-reception-fichier.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:actes-analyse-fichier-recu]
command=php /var/www/s2low/cron/actes-analyse-fichier-recu.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:actes-notification]
command=php /var/www/s2low/bin/console cron:notify-actes
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:actes-prepare-sae]
command=php /var/www/s2low/cron/actes-prepare-sae.php
autorestart=true
directory=/var/www
env=HOME="/var/www"


[program:actes-envoi-sae]
command=php /var/www/s2low/cron/actes-envoi-sae.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:actes-verif-transfert-sae]
command=php /var/www/s2low/cron/actes-verif-transfert-sae.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:helios-analyse-envoi]
command=php /var/www/s2low/cron/helios-analyse-fichier-a-envoyer.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:helios-reception]
command=php /var/www/s2low/cron/helios-reception.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:helios-envoi]
command=php /var/www/s2low/cron/helios-envoi.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:helios-analyse-reception]
command=php /var/www/s2low/cron/helios-analyse-fichier-recu.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:helios-prepare-sae]
command=php /var/www/s2low/cron/helios-prepare-sae.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:helios-envoi-sae]
command=php /var/www/s2low/cron/helios-envoi-sae.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:helios-verif-transfert-sae]
command=php /var/www/s2low/cron/helios-verif-transfert-sae.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:journal-vidange]
command=php /var/www/s2low/cron/journal-vidange.php
autorestart=true
directory=/var/www
env=HOME="/var/www"


[program:journal-request]
command=php /var/www/s2low/cron/journal-request.php
autorestart=true
directory=/var/www
env=HOME="/var/www"

[program:ipsec-monitor]
command=/var/www/s2low/script/divers/ipsec-monitor.sh /etc/ipsec.conf
autorestart=true
# FIXME
# user=root

[program:recup_crl]
command=php /var/www/s2low/cron/certificats-recuperateur.php
autorestart=true
# FIXME
# user=root