#Uniquement si on utilise la possibilite de recuperer les fichier OCRE pour les exporter vers un repertoire externe

# [program:ocre-export]
# command=php /var/www/s2low/cron/ocre-export.php
# directory=/var/www
# env=HOME="/var/www"
# autorestart=true
