[program:actes-antivirus]
command=php /app/bin/console worker:acte-antivirus
autorestart=true

[program:actes-analyse-fichier-a-envoyer]
command=php /app/bin/console worker:acte-analyse-fichier-a-envoyer
autorestart=true

[program:actes-envoi-fichier]
command=php /app/bin/console worker:acte-envoi-fichier
autorestart=true

[program:actes-envoi-ar]
command=php /app/bin/console worker:acte-envoi-ar
autorestart=true

[program:actes-reception-fichier]
command=php /app/bin/console worker:acte-reception-fichier
autorestart=true

[program:actes-analyse-fichier-recu]
command=php /app/bin/console worker:acte-analyse-fichier-recu
autorestart=true

[program:actes-notification]
command=php /app/bin/console worker:acte-notification
autorestart=true

[program:actes-prepare-sae]
command=timeout -k 60 3600 php /app/cron/actes-prepare-sae.php
autorestart=true

[program:actes-envoi-sae]
command=timeout -k 60 3600 php /app/cron/actes-envoi-sae.php
autorestart=true

[program:actes-verif-transfert-sae]
command=timeout -k 60 3600 php /app/cron/actes-verif-transfert-sae.php
autorestart=true
