[program:helios-store-pes-aller-in-cloud]
command=php /app/cron/helios-store-pes-aller-in-cloud.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:helios-menage]
command=php /app/cron/helios-menage.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:actes-store-envelope-in-cloud]
command=php /app/cron/actes-store-envelope-in-cloud.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:actes-menage-enveloppe]
command=php /app/cron/actes-menage-enveloppe.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:helios-menage-pes-acquit]
command=php /app/cron/helios-menage-pes-acquit.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:helios-store-pes-acquit-in-cloud]
command=php /app/cron/helios-store-pes-acquit-in-cloud.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:helios-menage-pes-retour]
command=php /app/cron/helios-menage-pes-retour.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:helios-store-pes-retour-in-cloud]
command=php /app/cron/helios-store-pes-retour-in-cloud.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:mailsec-store-files-in-cloud]
command=php /app/cron/mailsec-store-files-in-cloud.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s

[program:mailsec-menage]
command=php /app/cron/mailsec-menage.php
autostart=%(ENV_OPENSTACK_ENABLE)s
autorestart=%(ENV_OPENSTACK_ENABLE)s
