[group:actes-dgcl]
programs=actes-antivirus,actes-analyse-fichier-a-envoyer,actes-envoi-fichier,actes-envoi-ar,actes-reception-fichier,actes-analyse-fichier-recu,actes-notification

[group:actes-cloud]
programs=actes-store-envelope-in-cloud,actes-menage-enveloppe

[group:actes-sae]
programs=actes-prepare-sae,actes-envoi-sae,actes-verif-transfert-sae

[group:helios-dgfip]
programs=helios-analyse-envoi,helios-reception,helios-reception-passtrans,helios-envoi,helios-envoi-passtrans,helios-analyse-reception

[group:helios-cloud]
programs=helios-store-pes-aller-in-cloud,helios-menage,helios-menage-pes-acquit,helios-store-pes-acquit-in-cloud,helios-menage-pes-retour,helios-store-pes-retour-in-cloud

[group:helios-sae]
programs=helios-prepare-sae,helios-envoi-sae,helios-verif-transfert-sae

[group:journal]
programs=journal-vidange,journal-request

[group:mail-cloud]
programs=mailsec-store-files-in-cloud,mailsec-menage