[program:helios-analyse-envoi]
command=timeout -k 60 720 php /app/bin/console worker:helios-analyse-fichier-a-envoyer
autorestart=true

[program:helios-envoi]
command=php /app/bin/console worker:helios-envoi
numprocs=%(ENV_HELIOS_NB_FILES_ENVOI)s
process_name = %(program_name)s_%(process_num)02d
autorestart=true

[program:helios-envoi-passtrans]
command=php /app/bin/console worker:helios-envoi --usePasstrans
numprocs=%(ENV_HELIOS_NB_FILES_ENVOI_PASSTRANS)s
process_name = %(program_name)s_%(process_num)02d
autorestart=true

[program:helios-reception]
command=php /app/bin/console worker:helios-reception
autorestart=true

[program:helios-reception-passtrans]
command=php /app/bin/console worker:helios-reception --usePasstrans
autostart=%(ENV_HELIOS_PASSTRANS_RECEPTION_ENABLE)s
autorestart=%(ENV_HELIOS_PASSTRANS_RECEPTION_ENABLE)s

[program:helios-analyse-reception]
command=php /app/bin/console worker:helios-analyse-fichier-recu
autorestart=true

[program:helios-prepare-sae]
command=timeout -k 60 3600 php /app/cron/helios-prepare-sae.php
autorestart=true

[program:helios-envoi-sae]
command=timeout -k 60 3600 php /app/cron/helios-envoi-sae.php
autorestart=true

[program:helios-verif-transfert-sae]
command=timeout -k 60 3600 php /app/cron/helios-verif-transfert-sae.php
autorestart=true

[program:helios-purge]
command=php /app/script/helios/helios-purge-transaction.php do
autostart=%(ENV_HELIOS_PURGE_ENABLE)s
autorestart=%(ENV_HELIOS_PURGE_ENABLE)s