[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize
autostart=true
autorestart=true
stdout_logfile=/data/log/fpm-stdout.log
stderr_logfile=/data/log/fpm-stderr.log
pidfile=/data/run/fpm.pid