# Ce script est utilise dans la procedure d'install, ne pas effacer...

[eventlistener:process-failed]
command=php /app/bin/console worker:process-failed
events=PROCESS_STATE_FATAL
process_name=%(program_name)s_%(process_num)02d
numprocs=1
autostart=true
autorestart=unexpected

[program:journal-vidange]
command=php /app/cron/journal-vidange.php
autorestart=true

[program:journal-request]
command=php /app/bin/console cron:journal-request
autorestart=true
