<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="Simple_Type_Retour.xsd" />
  <xs:complexType name="TEnveloppe">
    <xs:annotation>
      <xs:documentation>L'enveloppe contient les éléments d'identification du flux (fichier, émetteur et récepteur)</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Parametres" type="TParametres">
        <xs:annotation>
          <xs:documentation>Caractéristiques du fichier</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Emetteur" type="TCarteVisite" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Carte de visite de l'émetteur</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Recepteur" type="TCarteVisite" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Carte de visite du récepteur</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TParametres">
    <xs:annotation>
      <xs:documentation>Caractéristiques du fichier</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Version" type="Base_Num2">
        <xs:annotation>
          <xs:documentation>Numéro de version du message. Ce numéro est relatif à l’enveloppe. Doit être valorisé à 1</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="TypFic" type="Base_Texte32">
        <xs:annotation>
          <xs:documentation>Code du type de fichier : 
- PES2R_DEP pour le PES_Retour Dépense</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="NomFic" type="Base_Texte100">
        <xs:annotation>
          <xs:documentation>Nom du fichier.
- pour le PES Retour Dépense : PES2R_DEP__TypeRestit_CodColl_CodBud_Codique_DateSituation_Date_Traitement_TimeStamp.xml.
TypeRestit = R pour flux de mandats rejetés/mis en instance, P pour flux périodique RR pour ré émission flux de mandats rejetés ou mis en instance, RP pour ré émission Flux périodiques.
CodColl = Code Collectivité
CodBud = CodBudget
Codique= codique du poste comptable
Date Situation : Date de l’extraction des éléments (Dte structure)
Date de traitement : date de constitution du flux
NumFlux : numéro du flux (il peut y avoir plusieurs flux de même type pour une date de situation donnée)
Nb Flux : nombre total de flux de même type pour une date de situation donnée
Time Stamp = Horodatage : AAAAMMJJhhmmss.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TCarteVisite">
    <xs:annotation>
      <xs:documentation>Carte de visite du partenaire émetteur / récepteur</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Sigle" type="Base_Texte32" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Sigle de l’émetteur / récepteur</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Adresse" type="Base_Texte38" minOccurs="0">
        <xs:annotation>
          <xs:documentation>Adresse physique de l’émetteur / récepteur</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
