#! /bin/bash
set -e

# Activation ou non de XDEBUG
if [ -z ${XDEBUG_ON} ]
then
    if [ -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ]
    then
        rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    fi
else
    docker-php-ext-enable xdebug
fi

/bin/bash /var/www/s2low/docker-resources/generate-config.sh > /etc/s2low/DockerSettings.php

/bin/bash /var/www/s2low/docker-resources/create-directory-structure.sh

# Pour HTMLPurifier qui marche pas sans son repertoire vide (et qui du coup est supprimé par git)
# TODO dans le dockerfile ?
mkdir -p /var/www/s2low/ext/standalone/HTMLPurifier/DefinitionCache/Serializer
chmod 777 /var/www/s2low/ext/standalone/HTMLPurifier/DefinitionCache/Serializer

# Génération fichier ssmtp.conf
/bin/bash /var/www/s2low/docker-resources/generate-ssmtp.conf.sh > /etc/ssmtp/ssmtp.conf


#A mettre dans le dockerfile ?
usermod -s /bin/bash www-data


if [ "${PUBLISH_SIMULATEUR}" = true ] ; then
    a2ensite simulateur
else
    a2dissite simulateur
fi

if [ "$LETSENCRYPT_DOMAIN" ] ; then
    if [ -f "/etc/apache2/ssl/fullchain.pem" ] ; then
            certbot renew
    else
        certbot --standalone --noninteractive --agree-to --preferred-challenges http -d ${LETSENCRYPT_DOMAIN} -m ${LETSENCRYPT_EMAIL} certonly
        ln -s /etc/letsencrypt/live/s2low.test.libriciel.fr/fullchain.pem /etc/apache2/ssl/
        ln -s /etc/letsencrypt/live/s2low.test.libriciel.fr/privkey.pem /etc/apache2/ssl/
    fi

fi


php /var/www/s2low/docker-resources/init-docker.php

exec "$@"
