#! /bin/bash
set -e

# TODO vérification de l'installation de composer ?

/bin/bash /var/www/s2low/docker-resources/generate-config.sh > /etc/s2low/DockerSettings.php

/bin/bash /var/www/s2low/docker-resources/create-directory-structure.sh

# Pour HTMLPurifier qui marche pas sans son repertoire vide (et qui du coup est supprimé par git)
# TODO dans le dockerfile ?
mkdir -p /var/www/s2low/ext/standalone/HTMLPurifier/DefinitionCache/Serializer
chmod 777 /var/www/s2low/ext/standalone/HTMLPurifier/DefinitionCache/Serializer

# Génération fichier ssmtp.conf
/bin/bash /var/www/s2low/docker-resources/generate-msmtp.conf.sh > /etc/msmtprc


#TODO A mettre dans le dockerfile ?
usermod -s /bin/bash www-data


if [ "${PUBLISH_SIMULATEUR}" = true ] ; then
    a2ensite simulateur
else
    a2dissite simulateur
fi

#TODO vérifier qu'il y a aussi LETSENCRYPT_EMAIL de définit
#voir si on peu s'assurer que le dossier letsencrypt est un point de montage
if [ "$LETSENCRYPT_DOMAIN" ] ; then
    if [ -f "/etc/apache2/ssl/fullchain.pem" ] ; then
            certbot renew
    else
        certbot --standalone --noninteractive --agree-to --preferred-challenges http -d ${LETSENCRYPT_DOMAIN} -m ${LETSENCRYPT_EMAIL} certonly
        ln -s /etc/letsencrypt/live/${LETSENCRYPT_DOMAIN}/fullchain.pem /etc/apache2/ssl/
        ln -s /etc/letsencrypt/live/${LETSENCRYPT_DOMAIN}/privkey.pem /etc/apache2/ssl/
    fi

fi

if [ -z "$DONT_RETRIEVE_VALIDCA" ] ; then

  # Ajout des ACs du ministère
  /usr/local/bin/recup_ac_ministere.sh /etc/s2low/ssl/ /etc/ssl/certs/
fi

if [ -z "$DONT_INIT_DATABASE" ] ; then
  #On attend que la base de données soit accessible avant de l'initialiser
  if [ ! ${POSTGRES_HOST} ] ; then
    POSTGRES_HOST="db"
  fi

  until nc -z -v -w30 ${POSTGRES_HOST} 5432
  do
    echo "Waiting for database connection..."
    sleep 5
  done

  php /var/www/s2low/docker-resources/init-docker.php

  if [ "$POSTGRES_DATABASE_TEST" ]; then
      php /var/www/s2low/docker-resources/init-bdd-test.php
  fi
fi
#On remet le bon propriétaire sur le log slow.log
chown -R www-data:www-data /data/log

exec "$@"
