#! /bin/bash
set -e

# Activation ou non de XDEBUG
if [ -z ${XDEBUG_ON} ]
then
    if [ -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ]
    then
        rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    fi
else
    docker-php-ext-enable xdebug
fi

/bin/bash /var/www/s2low/docker-resources/generate-config.sh > /etc/s2low/DockerSettings.php

/bin/bash /var/www/s2low/docker-resources/create-directory-structure.sh

# Pour HTMLPurifier qui marche pas sans son repertoire vide (et qui du coup est supprimé par git)
# TODO dans le dockerfile ?
mkdir -p /var/www/s2low/ext/standalone/HTMLPurifier/DefinitionCache/Serializer
chmod 777 /var/www/s2low/ext/standalone/HTMLPurifier/DefinitionCache/Serializer

# Génération fichier ssmtp.conf
/bin/bash /var/www/s2low/docker-resources/generate-ssmtp.conf.sh > /etc/ssmtp/ssmtp.conf


#A mettre dans le dockerfile ?
usermod -s /bin/bash www-data


php /var/www/s2low/docker-resources/init-docker.php

exec "$@"
