#! /bin/bash
set -e

# Utiliser pour creer un fichier de settings symfony en fonction des variables d'environnement (envoye par Docker)
#TODO : integrer les variables WEB_HTTP_PORT et WEB_HTTPS_PORT

cat <<EOF
APP_ENV=${APP_ENV:-test}
APP_SECRET=${APP_SECRET:-26d5b9f65f6caa90a7d55e57550e196c}
APP_DEBUG=${APP_DEBUG:-true}

DB_HOST=${POSTGRES_HOST:-db}
DB_USER=${POSTGRES_USER:-s2lowuser}
DB_PASSWORD=${POSTGRES_PASSWORD:-s2lowpassword}
DB_DATABASE=${POSTGRES_DB:-s2lowdb}

DB_HOST_TEST=${POSTGRES_HOST_TEST:-dbtest}
DB_USER_TEST=${POSTGRES_USER_TEST:-s2lowusertest}
DB_PASSWORD_TEST=${POSTGRES_PASSWORD_TEST:-s2lowpasswordtest}
DB_DATABASE_TEST=${POSTGRES_DATABASE_TEST:-s2lowdbtest}

MAILER_DSN="${MAILER_DSN:-smtp://maildev:1025?verify_peer=0}"

ACTES_APPLI_TRIGRAMME=${ACTES_APPLI_TRIGRAMME:-abc}

HELIOS_FTP_P_APPLI=${HELIOS_FTP_P_APPLI:-GHELPES2}

HELIOS_FTP_SERVER=${HELIOS_FTP_SERVER:-ftp}
HELIOS_FTP_PORT=${HELIOS_FTP_PORT:-21}
HELIOS_FTP_PASSIVE_MODE=${HELIOS_FTP_PASSIVE_MODE:-true}
HELIOS_FTP_CONNECTION_MODE=${HELIOS_FTP_CONNECTION_MODE:-false}
HELIOS_FTP_LOGIN=${HELIOS_FTP_LOGIN:-helios}
HELIOS_FTP_PASSWORD=${HELIOS_FTP_PASSWORD:-helios}
HELIOS_SENDING_DESTINATION=${HELIOS_SENDING_DESTINATION:-/entree/}
HELIOS_FTP_RESPONSE_SERVER_PATH=${HELIOS_FTP_RESPONSE_SERVER_PATH:-/sortie/}

HELIOS_PASSTRANS_SERVER=${HELIOS_PASSTRANS_SERVER:-ftp}
HELIOS_PASSTRANS_PORT=${HELIOS_PASSTRANS_PORT:-21}
HELIOS_PASSTRANS_PASSIVE_MODE=${HELIOS_PASSTRANS_PASSIVE_MODE:-true}
HELIOS_PASSTRANS_CONNECTION_MODE=${HELIOS_PASSTRANS_CONNECTION_MODE:-false}
HELIOS_PASSTRANS_LOGIN=${HELIOS_PASSTRANS_LOGIN:-helios-passtrans}
HELIOS_PASSTRANS_PASSWORD=${HELIOS_PASSTRANS_PASSWORD:-helios-passtrans}
HELIOS_PASSTRANS_SENDING_DESTINATION=${HELIOS_PASSTRANS_SENDING_DESTINATION:-/entree/}
HELIOS_PASSTRANS_RESPONSE_SERVER_PATH=${HELIOS_PASSTRANS_RESPONSE_SERVER_PATH:-/sortie/}

BEANSTAKLD_SERVER=${BEANSTAKLD_SERVER:-beanstalkd}
BEANSTAKLD_PORT=${BEANSTAKLD_PORT:-11300}

REDIS_SERVER=${REDIS_SERVER:-redis}
REDIS_PORT=${REDIS_PORT:-6379}

ANTIVIRUS_COMMAND=/usr/bin/clamdscan


#--------------------------------------------------------------------------------------------------

USE_PROD_NOTIFICATIONS=${USE_PROD_NOTIFICATIONS:-false}
WEBSITE="http://${S2LOW_WEBSITE:-s2low.docker.libriciel.fr}${WEB_HTTP_PORT/$WEB_HTTP_PORT/:}${WEB_HTTP_PORT:-}${S2LOW_URL_PATH:-}/"
WEBSITE_SSL="https://${S2LOW_WEBSITE:-s2low.docker.libriciel.fr}${WEB_HTTPS_PORT/$WEB_HTTPS_PORT/:}${WEB_HTTPS_PORT:-}${S2LOW_URL_PATH:-}/"
WEBSITE_MAIL="https://${S2LOW_WEBSITE_MAIL:-mail.s2low.docker.libriciel.fr}${WEB_HTTPS_PORT/$WEB_HTTPS_PORT/:}${WEB_HTTPS_PORT:-}/"
OPERATEUR_DE_TELETRANSMISSION="${OPERATEUR_DE_TELETRANSMISSION:-Libriciel SCOP}"
IMAGE_FOR_STAMP="${IMAGE_FOR_STAMP:-/var/www/s2low/public.ssl/custom/images/s2low-stamp.png}"
LIBERSIGN_INSTALLER="${LIBERSIGN_INSTALLER-https://libersign.libriciel.fr/make.sh}"

CONVERT_API_LOGINS_FROM_ISO=${CONVERT_API_LOGINS_FROM_ISO:-false}

ONLY_USE_VALIDCARGS=${ONLY_USE_VALIDCARGS:-false}

HELIOS_RETENTION_FICHIERS_NB_JOURS="${HELIOS_RETENTION_FICHIERS_NB_JOURS:-3650000}"

TDT_FROM_EMAIL="${TDT_FROM_EMAIL:-Tiers de télétransmission <s2low@s2low.docker.libriciel.fr>}"

ACTES_TDT_MAIL_ADDRESS="${ACTES_TDT_MAIL_ADDRESS:-s2low@s2low.docker.libriciel.fr}"
ACTES_IMAP_HOST="${ACTES_IMAP_HOST:-mail}"
ACTES_IMAP_PORT="${ACTES_IMAP_PORT:-143}"
ACTES_IMAP_LOGIN="${ACTES_IMAP_LOGIN:-s2low@s2low.docker.libriciel.fr}"
ACTES_IMAP_PASSWORD="${ACTES_IMAP_PASSWORD:-password}"
ACTES_IMAP_OPTIONS="${ACTES_IMAP_OPTIONS:-/imap/notls/novalidate-cert}"

ACTES_APPLI_NAME="${ACTES_APPLI_NAME:-TACT}"
ACTES_APPLI_QUADRIGRAMME="${ACTES_APPLI_QUADRIGRAMME:-TACT}"
ACTES_MAIL_BACKUP="${ACTES_MAIL_BACKUP:-}"
ACTES_COMMON_BROADCAST_EMAILS="${ACTES_COMMON_BROADCAST_EMAILS:-}"

ACTES_MINISTERE_URL="${ACTES_MINISTERE_URL:-http://simulateur/Simulateur/actesPost}"
ACTES_MINISTERE_AUTHENTICATION="${ACTES_MINISTERE_AUTHENTICATION:-NONE}"
ACTES_MINISTERE_LOGIN="${ACTES_MINISTERE_LOGIN:-}"
ACTES_MINISTERE_PASSWORD="${ACTES_MINISTERE_PASSWORD:-}"
ACTES_MINISTERE_CERTIFICATE="${ACTES_MINISTERE_CERTIFICATE:-}"
ACTES_MINISTERE_CERTIFICATE_KEY="${ACTES_MINISTERE_CERTIFICATE_KEY:-}"
ACTES_MINISTERE_CERTIFICATE_KEY_PASS="${ACTES_MINISTERE_CERTIFICATE_KEY_PASS:-}"
ACTES_MINISTERE_SERVER_CERTIFICATE_PATH="${ACTES_MINISTERE_SERVER_CERTIFICATE_PATH:-}"
ACTES_MINISTERE_ADAPT_PROTOCOL="${ACTES_MINISTERE_ADAPT_PROTOCOL:-false}"

OPENSTACK_ENABLE=${OPENSTACK_ENABLE:-false}
ACTES_OPENSTACK_AUTHENTICATION_URL_V3="${ACTES_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}"
ACTES_OPENSTACK_USERNAME="${ACTES_OPENSTACK_USERNAME}"
ACTES_OPENSTACK_PASSWORD="${ACTES_OPENSTACK_PASSWORD}"
ACTES_OPENSTACK_TENANT="${ACTES_OPENSTACK_TENANT}"
ACTES_OPENSTACK_REGION="${ACTES_OPENSTACK_REGION}"
ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX="${ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX}"

HELIOS_OPENSTACK_AUTHENTICATION_URL_V3="${HELIOS_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}"
HELIOS_OPENSTACK_USERNAME="${HELIOS_OPENSTACK_USERNAME}"
HELIOS_OPENSTACK_PASSWORD="${HELIOS_OPENSTACK_PASSWORD}"
HELIOS_OPENSTACK_TENANT="${HELIOS_OPENSTACK_TENANT}"
HELIOS_OPENSTACK_REGION="${HELIOS_OPENSTACK_REGION}"
HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX="${HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX}"

HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3="${HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}"
HELIOS_ACQUIT_OPENSTACK_USERNAME="${HELIOS_ACQUIT_OPENSTACK_USERNAME}"
HELIOS_ACQUIT_OPENSTACK_PASSWORD="${HELIOS_ACQUIT_OPENSTACK_PASSWORD}"
HELIOS_ACQUIT_OPENSTACK_TENANT="${HELIOS_ACQUIT_OPENSTACK_TENANT}"
HELIOS_ACQUIT_OPENSTACK_REGION="${HELIOS_ACQUIT_OPENSTACK_REGION}"
HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX="${HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX}"

HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3="${HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}"
HELIOS_RETOUR_OPENSTACK_USERNAME="${HELIOS_RETOUR_OPENSTACK_USERNAME}"
HELIOS_RETOUR_OPENSTACK_PASSWORD="${HELIOS_RETOUR_OPENSTACK_PASSWORD}"
HELIOS_RETOUR_OPENSTACK_TENANT="${HELIOS_RETOUR_OPENSTACK_TENANT}"
HELIOS_RETOUR_OPENSTACK_REGION="${HELIOS_RETOUR_OPENSTACK_REGION}"
HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX="${HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX}"

MAILSEC_OPENSTACK_AUTHENTICATION_URL_V3="${MAILSEC_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}"
MAILSEC_OPENSTACK_USERNAME="${MAILSEC_OPENSTACK_USERNAME}"
MAILSEC_OPENSTACK_PASSWORD="${MAILSEC_OPENSTACK_PASSWORD}"
MAILSEC_OPENSTACK_TENANT="${MAILSEC_OPENSTACK_TENANT}"
MAILSEC_OPENSTACK_REGION="${MAILSEC_OPENSTACK_REGION}"
MAILSEC_OPENSTACK_SWIFT_CONTAINER_PREFIX="${MAILSEC_OPENSTACK_SWIFT_CONTAINER_PREFIX}"


#A vérifier
PADES_VALID_URL="${PADES_VALID_URL:-http://pades-valid:8080}"
PDF_STAMP_URL="${PDF_STAMP_URL:-http://pdf-stamp:8080}"

HELIOS_OCRE_FILE_PATH='/data/tdt-workspace/helios/ocre/'
EXPORT_LOGS_DIRECTORY='/data/tdt-workspace/logs-export/'

EMAIL_ADMIN_TECHNIQUE="${EMAIL_ADMIN_TECHNIQUE:-noreply@locahost}"

ACTES_ALWAYS_CAN_VALIDATE=${ACTES_ALWAYS_CAN_VALIDATE:-false}

USE_LEGACY_BORDEREAU_MODEL=${USE_LEGACY_BORDEREAU_MODEL:-true}

USE_LEGACY_SECURE_MAIL_FIELDS=${USE_LEGACY_SECURE_MAIL_FIELDS:-false}
MAIL_TEDETIS_FROM="${MAIL_TEDETIS_FROM:-s2low@s2low.docker.libriciel.fr}"
MAIL_SECURE_DESCRIPTION="${MAIL_SECURE_DESCRIPTION}"
MAIL_MESSAGE="${MAIL_MESSAGE:-Vous avez reçu un courrier recommandé par S2LOW}"
MAIL_TEXT="${MAIL_TEXT:-Bonjour,

Un courrier recommandé avec d’éventuelles pièces jointes vous a été transmis par la plateforme sécurisée de l’ADULLACT.
Nous vous proposons de cliquer sur le lien suivant pour accéder au courrier recommandé et confirmer la réception :
accés au courrier recommandé.}"

HELIOS_USE_PASSTRANS_AS_DEFAULT=${HELIOS_USE_PASSTRANS_AS_DEFAULT:-false}

WORKSPACE_DIRECTORY="/data/tdt-workspace/"
# Répertoire de stockage des fichiers envoyés par les utilisateurs (archives .tar.gz)
ACTES_FILES_UPLOAD_ROOT='/data/tdt-workspace/actes/uploads'
# Répertoire de stockage des vieux fichiers envoyés par les utilisateurs (archives .tar.gz) sans transaction associée
ACTES_ENVELOPPE_SANSTRANSACTION='/data/tdt-workspace/actes/sans_transaction'
# Répertoire de stockage des fichiers constituant les lots
ACTES_BATCHES_UPLOAD_ROOT='/data/tdt-workspace/actes/batchs'
# Répertoire temporaire de stockage des réponses du ministère par mail
ACTES_RESPONSE_TMP_LOCAL_PATH='/data/tdt-workspace/actes/response_tmp'
# Répertoire temporaire de stockage des réponses en erreur du ministère
ACTES_RESPONSE_ERROR_PATH='/data/tdt-workspace/actes/response_error'

HELIOS_FILES_ROOT='/data/tdt-workspace/helios/'
# Répertoire de stockage des fichiers envoyés par les utilisateurs
HELIOS_FILES_UPLOAD_ROOT='/data/tdt-workspace/helios/sending/'
# Repertoire de stockage des reponses
HELIOS_RESPONSES_ROOT='/data/tdt-workspace/helios/response/'
# Repertoire de stockage des reponses en erreur
HELIOS_RESPONSES_ERROR_PATH='/data/tdt-workspace/helios/response_error/'
# Repertoire de stockage des fichiers temporaires à envoyer au FTP
HELIOS_FILES_UPLOAD_TMP='/data/tdt-workspace/helios/sending-tmp/'
HELIOS_COUNTER_FILE='/data/tdt-workspace/helios/counter.txt'

EOF