#! /bin/bash
set -e

# Utiliser pour creer un fichier de settings en fonction des variables d'environnement (envoye par Docker)
#TODO : integrer les variables WEB_HTTP_PORT et WEB_HTTPS_PORT

cat <<EOF
<?php

define("WEBSITE","http://${S2LOW_WEBSITE:-s2low.docker.libriciel.fr}${WEB_HTTP_PORT/$WEB_HTTP_PORT/:}${WEB_HTTP_PORT:-}${S2LOW_URL_PATH:-}/");
define("WEBSITE_SSL","https://${S2LOW_WEBSITE:-s2low.docker.libriciel.fr}${WEB_HTTPS_PORT/$WEB_HTTPS_PORT/:}${WEB_HTTPS_PORT:-}${S2LOW_URL_PATH:-}/");
define("IMAGE_FOR_STAMP","${IMAGE_FOR_STAMP:-/var/www/s2low/public.ssl/custom/images/s2low-stamp.png}");
define('DB_HOST', "${POSTGRES_HOST:-db}");
define('DB_USER', "${POSTGRES_USER:-s2lowuser}");
define('DB_PASSWORD', "${POSTGRES_PASSWORD:-s2lowpassword}");
define('DB_DATABASE', "${POSTGRES_DB:-s2lowdb}");

define('DB_HOST_TEST', "${POSTGRES_HOST_TEST:-dbtest}");
define('DB_USER_TEST', "${POSTGRES_USER_TEST:-s2lowusertest}");
define('DB_PASSWORD_TEST', "${POSTGRES_PASSWORD_TEST:-s2lowpasswordtest}");
define('DB_DATABASE_TEST', "${POSTGRES_DATABASE_TEST:-s2lowdbtest}");

define("HELIOS_FTP_SERVER","${HELIOS_FTP_SERVER:-ftp}");
define("HELIOS_FTP_PORT","${HELIOS_FTP_PORT:-21}");
define("HELIOS_FTP_PASSIVE_MODE", ${HELIOS_FTP_PASSIVE_MODE:-false});
define("HELIOS_SENDING_MODE_DEMO", ${HELIOS_SENDING_MODE_DEMO:-true});
define("HELIOS_FTP_PST_MODE", ${HELIOS_FTP_PST_MODE:-false});
define("HELIOS_FTP_P_APPLI", "${HELIOS_FTP_P_APPLI}");
define('HELIOS_FTP_LOGIN',"${HELIOS_FTP_LOGIN:-helios}");
define('HELIOS_FTP_PASSWORD',"${HELIOS_FTP_PASSWORD:-helios}");
define("HELIOS_SENDING_DESTINATION","${HELIOS_SENDING_DESTINATION:-/entree/}");
define("HELIOS_FTP_RESPONSE_SERVER_PATH","${HELIOS_FTP_RESPONSE_SERVER_PATH:-/sortie/}");
define("HELIOS_FTP_RESPONSE_TMP_LOCAL_PATH","${HELIOS_FTP_RESPONSE_TMP_LOCAL_PATH:-/sortie/}");

define('ACTES_TDT_MAIL_ADDRESS', "${ACTES_IMAP_LOGIN:-s2low@s2low.docker.libriciel.fr}");
define('ACTES_IMAP_HOST', "${ACTES_IMAP_HOST:-mail}");
define('ACTES_IMAP_LOGIN', "${ACTES_IMAP_LOGIN:-s2low@s2low.docker.libriciel.fr}");
define('ACTES_IMAP_PASSWORD', "${ACTES_IMAP_PASSWORD:-password}");

define("ACTES_OPENSTACK_AUTHENTICATION_URL_V3","${ACTES_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}");
define("ACTES_OPENSTACK_USERNAME","${ACTES_OPENSTACK_USERNAME}");
define("ACTES_OPENSTACK_PASSWORD","${ACTES_OPENSTACK_PASSWORD}");
define("ACTES_OPENSTACK_TENANT","${ACTES_OPENSTACK_TENANT}");
define("ACTES_OPENSTACK_REGION","${ACTES_OPENSTACK_REGION}");
define("ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX","${ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX}");

define("HELIOS_OPENSTACK_AUTHENTICATION_URL_V3","${HELIOS_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}");
define("HELIOS_OPENSTACK_USERNAME","${HELIOS_OPENSTACK_USERNAME}");
define("HELIOS_OPENSTACK_PASSWORD","${HELIOS_OPENSTACK_PASSWORD}");
define("HELIOS_OPENSTACK_TENANT","${HELIOS_OPENSTACK_TENANT}");
define("HELIOS_OPENSTACK_REGION","${HELIOS_OPENSTACK_REGION}");
define("HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX","${HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX}");

define("HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3","${HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}");
define("HELIOS_ACQUIT_OPENSTACK_USERNAME","${HELIOS_ACQUIT_OPENSTACK_USERNAME}");
define("HELIOS_ACQUIT_OPENSTACK_PASSWORD","${HELIOS_ACQUIT_OPENSTACK_PASSWORD}");
define("HELIOS_ACQUIT_OPENSTACK_TENANT","${HELIOS_ACQUIT_OPENSTACK_TENANT}");
define("HELIOS_ACQUIT_OPENSTACK_REGION","${HELIOS_ACQUIT_OPENSTACK_REGION}");
define("HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX","${HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX}");

define("HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3","${HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}");
define("HELIOS_RETOUR_OPENSTACK_USERNAME","${HELIOS_RETOUR_OPENSTACK_USERNAME}");
define("HELIOS_RETOUR_OPENSTACK_PASSWORD","${HELIOS_RETOUR_OPENSTACK_PASSWORD}");
define("HELIOS_RETOUR_OPENSTACK_TENANT","${HELIOS_RETOUR_OPENSTACK_TENANT}");
define("HELIOS_RETOUR_OPENSTACK_REGION","${HELIOS_RETOUR_OPENSTACK_REGION}");
define("HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX","${HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX}");

define("MAILSEC_OPENSTACK_AUTHENTICATION_URL_V3","${MAILSEC_OPENSTACK_AUTHENTICATION_URL_V3:-https://auth.cloud.ovh.net/v3}");
define("MAILSEC_OPENSTACK_USERNAME","${MAILSEC_OPENSTACK_USERNAME}");
define("MAILSEC_OPENSTACK_PASSWORD","${MAILSEC_OPENSTACK_PASSWORD}");
define("MAILSEC_OPENSTACK_TENANT","${MAILSEC_OPENSTACK_TENANT}");
define("MAILSEC_OPENSTACK_REGION","${MAILSEC_OPENSTACK_REGION}");
define("MAILSEC_OPENSTACK_SWIFT_CONTAINER_PREFIX","${MAILSEC_OPENSTACK_SWIFT_CONTAINER_PREFIX}");



define("IMAP_SERVER","${SMTP_SERVER:-mailsec}");
define("IMAP_LOGIN","${IMAP_LOGIN:-s2low-mailsec@s2low.docker.libriciel.fr}");
define("IMAP_PASS","${IMAP_PASS:-s2low-mailsec}");

#A vérifier
#define('ANTIVIRUS_COMMAND','/usr/bin/clamdscan --fdpass --stream');
define('PADES_VALID_URL', "${PADES_VALID_URL:-http://pades-valid:8080}");
define('PDF_STAMP_URL', "${PDF_STAMP_URL:-http://pdf-stamp:8080}");

define('HELIOS_OCRE_FILE_PATH','/data/tdt-workspace/helios/ocre/');
define('EXPORT_LOGS_DIRECTORY','/data/tdt-workspace/logs-export/');

define('EMAIL_ADMIN_TECHNIQUE',"${EMAIL_ADMIN_TECHNIQUE:-noreply@locahost}");

define('MODE_BEANSTALKD',true);

define("MODE_REDIS",true);
define("REDIS_SERVER","${REDIS_SERVER:-redis}");
define("REDIS_PORT","${REDIS_PORT:-6379}");

define('ACTES_ALWAYS_CAN_VALIDATE',${ACTES_ALWAYS_CAN_VALIDATE:-false});

define("ACTES_TYPE_PAR_NATURE",${ACTES_TYPE_PAR_NATURE:-true});
define("ACTES_TYPE_PJ_IS_MANDATORY",${ACTES_TYPE_PJ_IS_MANDATORY:-true});

define("USE_LEGACY_BORDEREAU_MODEL",${USE_LEGACY_BORDEREAU_MODEL:-true});
EOF
