[supervisord]
nodaemon=true

[program:cron]
command = /usr/sbin/cron -f -L 15
user = root
autostart = true
autorestart = true


[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"
stdout_events_enabled=true
stderr_events_enabled=true
autorestart=true

[program:actes-antivirus]
command=php /var/www/s2low/cron/antivirus-check.php
autorestart=true

[program:actes-analyse-fichier-a-envoyer]
command=php /var/www/s2low/cron/actes-analyse-fichier-a-envoyer.php
autorestart=true

[program:actes-envoi-fichier]
command=php /var/www/s2low/cron/actes-envoi-fichier.php
autorestart=true

[program:actes-envoi-ar]
command=php /var/www/s2low/cron/actes-envoi-ar.php
autorestart=true

[program:actes-reception-fichier]
command=php /var/www/s2low/cron/actes-reception-fichier.php
autorestart=true

[program:actes-analyse-fichier-recu]
command=php /var/www/s2low/cron/actes-analyse-fichier-recu.php
autorestart=true

[program:actes-envoi-sae.php]
command=php /var/www/s2low/cron/actes-envoi-sae.php
autorestart=true

[program:pastell-verif-transfert-sae-actes.php]
command=php /var/www/s2low/cron/pastell-verif-transfert-sae-actes.php
autorestart=true

[program:helios-analyse-envoi]
command=php /var/www/s2low/cron/helios-analyse-fichier-a-envoyer.php
autorestart=true

[program:helios-envoi]
command=php /var/www/s2low/cron/helios-envoi-fichier.php
autorestart=true

[program:helios-reception]
command=php /var/www/s2low/cron/reception-fichier-helios.php
autorestart=true

[program:helios-analyse-reception]
command=php /var/www/s2low/cron/helios-analyse-fichier-recu.php
autorestart=true

[program:notification]
command=php /var/www/s2low/cron/notification.php
autorestart=true

[program:helios-store-pes-aller-in-cloud]
command=php /var/www/s2low/cron/helios-store-pes-aller-in-cloud.php
autorestart=true

[program:helios-delete-old-pes-aller.php]
command=php /var/www/s2low/cron/helios-delete-old-pes-aller.php 1
autorestart=true

[program:helios-envoi-sae.php]
command=php /var/www/s2low/cron/helios-envoi-sae.php
autorestart=true

[program:pastell-verif-transfert-sae-helios.php]
command=php /var/www/s2low/cron/pastell-verif-transfert-sae-actes.php
autorestart=true