[supervisord]
nodaemon=true

[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"
stdout_events_enabled=true
stderr_events_enabled=true
autorestart=true

[program:helios-analyse-envoi]
command=php /var/www/s2low/cron/helios-analyse-fichier-a-envoyer.php
autorestart=true

[program:helios-envoi]
command=php /var/www/s2low/cron/helios-envoi-fichier.php
autorestart=true

[program:helios-reception]
command=php /var/www/s2low/cron/reception-fichier-helios.php
autorestart=true

[program:helios-analyse-reception]
command=php /var/www/s2low/cron/helios-analyse-fichier-recu.php
autorestart=true

[program:actes-antivirus]
command=php /var/www/s2low/cron/antivirus-check.php
autorestart=true


