parameters:
  app.database_name: '%env(POSTGRES_DATABASE_TEST)%'
  app.database_host: '%env(POSTGRES_HOST_TEST)%'
  app.database_login: '%env(POSTGRES_USER_TEST)%'
  app.database_password: '%env(POSTGRES_PASSWORD_TEST)%'

services:
  S2low\Command\Helios\Workers\HeliosAnalyseFichierAEnvoyerCommand:
    public: true
    autowire: true
    autoconfigure: true
