parameters:
  app.database_name: '%env(POSTGRES_DATABASE_TEST)%'
  app.database_host: '%env(POSTGRES_HOST_TEST)%'
  app.database_login: '%env(POSTGRES_USER_TEST)%'
  app.database_password: '%env(POSTGRES_PASSWORD_TEST)%'
  app.cloud.parameters.endpoint: ''
  app.cloud.parameters.credential.key: ''
  app.cloud.parameters.credential.secret: ''
  app.openstack_enable: false
  app.helios_use_passtrans_as_default: false
  app.actes.files_upload_root: '/tmp'
  app.mail.tdt_from_email: 'Tiers de télétransmission <s2low@s2low.docker.libriciel.fr>'
  app.mail.email_admin_technique: 'noreply@libriciel.net'
  app.log.file: '/data/log/s2low.log'
  app.cloud_storage_enabled: false
  app.cloud_bucket.acte_enveloppe: ''
  app.cloud_bucket.pes_aller: ''
  app.cloud_bucket.pes_acquit: ''
  app.cloud_bucket.pes_retour: ''
  app.cloud_bucket.mailsec: ''
  app.envelope_submission_enabled: true
services:
  _defaults:
    autowire: true
    autoconfigure: true
