parameters:
  actes.ministere.url.: 'http://simulateur/Simulateur/actesPost'
  actes.ministere.url.authentification_type: 'NONE'
  actes.ministere.url.login: ''
  actes.ministere.url.password: ''
  actes.ministere.url.client_certificat: ''
  actes.ministere.url.client_certificate_key: ''
  actes.ministere.url.client_certificate_key_password: ''
  actes.ministere.url.server_certificate_path: ''
  actes.ministere.url.adapt_protocol: 'false'
