parameters:
  actes:
    ministere:
      url: '%env(ACTES_MINISTERE_URL)%'
      authentification_type: '%env(ACTES_MINISTERE_AUTHENTICATION)%'
      login: '%env(ACTES_MINISTERE_LOGIN)%'
      password: '%env(ACTES_MINISTERE_PASSWORD)%'
      client_certificat: '%env(ACTES_MINISTERE_CERTIFICATE)%'
      client_certificate_key: '%env(ACTES_MINISTERE_CERTIFICATE_KEY)%'
      client_certificate_key_password: '%env(ACTES_MINISTERE_CERTIFICATE_KEY_PASS)%'
      server_certificate_path: '%env(ACTES_MINISTERE_SERVER_CERTIFICATE_PATH)%'
      adapt_protocol: '%env(ACTES_MINISTERE_ADAPT_PROTOCOL)%'
