# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true

  S2low\:
    resource: '../src/*'
    exclude: '../src/{Kernel.php,Command}'

  S2low\Legacy\LegacyRouteLoader:
    tags: [routing.loader]

  S2low\Controller\LegacyController:
    public: true