parameters:
  cloud_provider:
    actes:
      url: '%env(ACTES_OPENSTACK_AUTHENTICATION_URL_V3)'
      username: '%env(ACTES_OPENSTACK_USERNAME)'
      password: '%env(ACTES_OPENSTACK_PASSWORD)'
      tenant: '%env(ACTES_OPENSTACK_TENANT)'
      region: '%env(ACTES_OPENSTACK_REGION)'
      container_prefix: '%env(ACTES_OPENSTACK_SWIFT_CONTAINER_PREFIX)'
    helios_aller:
      url: '%env(HELIOS_OPENSTACK_AUTHENTICATION_URL_V3)'
      username: '%env(HELIOS_OPENSTACK_USERNAME)'
      password: '%env(HELIOS_OPENSTACK_PASSWORD)'
      tenant: '%env(HELIOS_OPENSTACK_TENANT)'
      region: '%env(HELIOS_OPENSTACK_REGION)'
      container_prefix: '%env(HELIOS_OPENSTACK_SWIFT_CONTAINER_PREFIX)'
    helios_acquit:
      url: '%env(HELIOS_ACQUIT_OPENSTACK_AUTHENTICATION_URL_V3)'
      username: '%env(HELIOS_ACQUIT_OPENSTACK_USERNAME)'
      password: '%env(HELIOS_ACQUIT_OPENSTACK_PASSWORD)'
      tenant: '%env(HELIOS_ACQUIT_OPENSTACK_TENANT)'
      region: '%env(HELIOS_ACQUIT_OPENSTACK_REGION)'
      container_prefix: '%env(HELIOS_ACQUIT_OPENSTACK_SWIFT_CONTAINER_PREFIX)'
    helios_retour:
      url: '%env(HELIOS_RETOUR_OPENSTACK_AUTHENTICATION_URL_V3)'
      username: '%env(HELIOS_RETOUR_OPENSTACK_USERNAME)'
      password: '%env(HELIOS_RETOUR_OPENSTACK_PASSWORD)'
      tenant: '%env(HELIOS_RETOUR_OPENSTACK_TENANT)'
      region: '%env(HELIOS_RETOUR_OPENSTACK_REGION)'
      container_prefix: '%env(HELIOS_RETOUR_OPENSTACK_SWIFT_CONTAINER_PREFIX)'
    mailsec:
      url: '%env(MAILSEC_OPENSTACK_AUTHENTICATION_URL_V3)'
      username: '%env(MAILSEC_OPENSTACK_USERNAME)'
      password: '%env(MAILSEC_OPENSTACK_PASSWORD)'
      tenant: '%env(MAILSEC_OPENSTACK_TENANT)'
      region: '%env(MAILSEC_OPENSTACK_REGION)'
      container_prefix: '%env(MAILSEC_OPENSTACK_SWIFT_CONTAINER_PREFIX)'
