imports:
  - { resource: services_actes.yaml }
  - { resource: services_cloud_provider.yaml }
parameters:
  app.antivirus_command: '/usr/bin/clamdscan'
  app.helios_passtrans_server: '%env(HELIOS_PASSTRANS_SERVER)%'
  app.helios_passtrans_port: '%env(HELIOS_PASSTRANS_PORT)%'
  app.helios_passtrans_passive_mode: '%env(HELIOS_PASSTRANS_PASSIVE_MODE)%'
  app.helios_passtrans_connection_mode: '%env(HELIOS_PASSTRANS_CONNECTION_MODE)%'
  app.helios_passtrans_login: '%env(HELIOS_PASSTRANS_LOGIN)%'
  app.helios_passtrans_password: '%env(HELIOS_PASSTRANS_PASSWORD)%'
  app.helios_passtrans_sending_destination: '%env(HELIOS_PASSTRANS_SENDING_DESTINATION)%'
  app.helios_passtrans_response_server_path: '%env(HELIOS_PASSTRANS_RESPONSE_SERVER_PATH)%'
  app.helios_ftp_p_appli: '%env(HELIOS_FTP_P_APPLI)%'
  app.helios_ftp_server: '%env(HELIOS_FTP_SERVER)%'
  app.helios_ftp_port: '%env(HELIOS_FTP_PORT)%'
  app.helios_ftp_passive_mode: '%env(HELIOS_FTP_PASSIVE_MODE)%'
  app.helios_ftp_connection_mode: '%env(HELIOS_FTP_CONNECTION_MODE)%'
  app.helios_ftp_login: '%env(HELIOS_FTP_LOGIN)%'
  app.helios_ftp_password: '%env(HELIOS_FTP_PASSWORD)%'
  app.helios_ftp_response_server_path: '%env(HELIOS_FTP_RESPONSE_SERVER_PATH)%'
