parameters:
  actes.ministere.env_url: '%env(ACTES_MINISTERE_URL)%'
  actes.ministere.url: '%actes.ministere.env_url%'
  actes.ministere.authentification_type.env_url: '%env(ACTES_MINISTERE_AUTHENTICATION)%'
  actes.ministere.authentification_type: '%actes.ministere.authentification_type.env_url%'
  actes.ministere.login.env_url: '%env(ACTES_MINISTERE_LOGIN)%'
  actes.ministere.login: '%actes.ministere.login.env_url%'
  actes.ministere.password.env_url: '%env(ACTES_MINISTERE_PASSWORD)%'
  actes.ministere.password: '%actes.ministere.password.env_url%'
  actes.ministere.client_certificat.env_url: '%env(ACTES_MINISTERE_CERTIFICATE)%'
  actes.ministere.client_certificat: '%actes.ministere.client_certificat.env_url%'
  actes.ministere.client_certificate_key.env_url: '%env(ACTES_MINISTERE_CERTIFICATE_KEY)%'
  actes.ministere.client_certificate_key: '%actes.ministere.client_certificate_key.env_url%'
  actes.ministere.client_certificate_key_password.env_url: '%env(ACTES_MINISTERE_CERTIFICATE_KEY_PASS)%'
  actes.ministere.client_certificate_key_password: '%actes.ministere.client_certificate_key_password.env_url%'
  actes.ministere.server_certificate_path.env_url: '%env(ACTES_MINISTERE_SERVER_CERTIFICATE_PATH)%'
  actes.ministere.server_certificate_path: '%actes.ministere.server_certificate_path.env_url%'
  actes.ministere.adapt_protocol.env_url: '%env(ACTES_MINISTERE_ADAPT_PROTOCOL)%'
  actes.ministere.adapt_protocol: '%actes.ministere.adapt_protocol.env_url%'
