parameters:
  actes.ministere.url.url: '%env(ACTES_MINISTERE_URL)%'
  actes.ministere.url.authentification_type: '%env(ACTES_MINISTERE_AUTHENTICATION)%'
  actes.ministere.url.login: '%env(ACTES_MINISTERE_LOGIN)%'
  actes.ministere.url.password: '%env(ACTES_MINISTERE_PASSWORD)%'
  actes.ministere.url.client_certificat: '%env(ACTES_MINISTERE_CERTIFICATE)%'
  actes.ministere.url.client_certificate_key: '%env(ACTES_MINISTERE_CERTIFICATE_KEY)%'
  actes.ministere.url.client_certificate_key_password: '%env(ACTES_MINISTERE_CERTIFICATE_KEY_PASS)%'
  actes.ministere.url.server_certificate_path: '%env(ACTES_MINISTERE_SERVER_CERTIFICATE_PATH)%'
  actes.ministere.url.adapt_protocol: '%env(ACTES_MINISTERE_ADAPT_PROTOCOL)%'
