#! /bin/sh
#
# Script for managing firewall rules

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

IPTABLES=/sbin/iptables

test -x $IPTABLES || exit 0

EXT=eth0

iptables_start() {
  echo "1" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
  echo "1" > /proc/sys/net/ipv4/icmp_ignore_bogus_error_responses
  echo "1" > /proc/sys/net/ipv4/conf/all/log_martians
  echo "0" > /proc/sys/net/ipv4/conf/all/accept_source_route
  echo "0" > /proc/sys/net/ipv4/conf/all/accept_redirects

  $IPTABLES -P INPUT DROP
  $IPTABLES -P OUTPUT DROP
  $IPTABLES -P FORWARD DROP

  $IPTABLES -N droplog

  # Autorise tout le trafic sur la loopback
  $IPTABLES -A INPUT -i lo -j ACCEPT
  $IPTABLES -A OUTPUT -o lo -j ACCEPT

  # S'assurer que les connexions générant un état NEW sont bien des paquets SYN
  $IPTABLES -A INPUT -i $EXT -p tcp ! --syn -m state --state NEW -j droplog

  # Refuse les fragments
  $IPTABLES -A INPUT -i $EXT -f -j LOG --log-prefix "IPTABLES FRAGMENTS: "
  $IPTABLES -A INPUT -i $EXT -f -j DROP

  # Limiter les scanners SSH
  $IPTABLES -A INPUT -i $EXT -p tcp --dport 22 -m state --state NEW -m recent --set --name SSH
  $IPTABLES -A INPUT -i $EXT -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 60 --hitcount 5 --rttl --name SSH -j DROP

  ###### !!!!!!!!!!!!!!!!!!!! ######
  ######    NE PAS ENLEVER    ######
  ###### !!!!!!!!!!!!!!!!!!!! ######
  # Accepte les connexions SSH
  $IPTABLES -A INPUT -i $EXT -p tcp --dport 22 -m state --state NEW,ESTABLISHED -j ACCEPT
  $IPTABLES -A OUTPUT -o $EXT -p tcp --sport 22 -m state --state ESTABLISHED -j ACCEPT
  ###### !!!!!!!!!!!!!!!!!!!! ######
  ###### !!!!!!!!!!!!!!!!!!!! ######
  
  # Autoriser le HTTP sortant (mise a jour apt-get)
  $IPTABLES -A INPUT -i $EXT -p tcp --sport 80 -m state --state ESTABLISHED -j ACCEPT
  $IPTABLES -A OUTPUT -o $EXT -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT

  # Autoriser le HTTPS sortant (appli TeDeTis)
  $IPTABLES -A INPUT -i $EXT -p tcp --sport 443 -m state --state ESTABLISHED -j ACCEPT
  $IPTABLES -A OUTPUT -o $EXT -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT

  # autoriser les échanges SMTP (dans les deux sens)
  $IPTABLES -A INPUT -i $EXT -p tcp --dport 25 -m state --state NEW,ESTABLISHED -j ACCEPT
  $IPTABLES -A OUTPUT -o $EXT -p tcp --sport 25 -m state --state ESTABLISHED -j ACCEPT
  $IPTABLES -A OUTPUT -o $EXT -p tcp --dport 25 -m state --state NEW,ESTABLISHED -j ACCEPT
  $IPTABLES -A INPUT -i $EXT -p tcp --sport 25 -m state --state ESTABLISHED -j ACCEPT

  # Autorise le NTP sortant
  $IPTABLES -A INPUT -i $EXT -p udp -m state --state ESTABLISHED --sport 123 -j ACCEPT
  $IPTABLES -A OUTPUT -o $EXT -p udp -m state --state NEW,ESTABLISHED --dport 123 -j ACCEPT

  # Accepte les requètes DNS sortantes
  $IPTABLES -A OUTPUT -o $EXT -p udp -m state --state NEW,ESTABLISHED --dport 53 -j ACCEPT
  $IPTABLES -A INPUT -i $EXT -p udp -m state --state ESTABLISHED --sport 53 -j ACCEPT
  $IPTABLES -A OUTPUT -o $EXT -p tcp -m state --state NEW,ESTABLISHED --dport 53 -j ACCEPT
  $IPTABLES -A INPUT -i $EXT -p tcp -m state --state ESTABLISHED --sport 53 -j ACCEPT

  # Accepte les connexions sur les services hébergés :
  # port 80 <=> HTTP
  # port 443 <=> HTTPS
  $IPTABLES -A INPUT -i $EXT -p tcp -m state --state NEW,ESTABLISHED --match multiport --destination-ports 80,443 -j ACCEPT
  $IPTABLES -A OUTPUT -o $EXT -p tcp -m state --state ESTABLISHED --match multiport --source-ports 80,443 -j ACCEPT

  # DROP le reste
  $IPTABLES -A INPUT -j droplog
  $IPTABLES -A OUTPUT -j droplog

  # Chaine droplog
  $IPTABLES -A droplog -m limit --limit 2/s --limit-burst 10 -j LOG --log-prefix "IPTABLES: "
  $IPTABLES -A droplog -j DROP
}

iptables_stop() {
  $IPTABLES -F
  $IPTABLES -t nat -F
  $IPTABLES -X

  echo "0" > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
  echo "0" > /proc/sys/net/ipv4/conf/all/log_martians 

  $IPTABLES -P INPUT ACCEPT
  $IPTABLES -P OUTPUT ACCEPT
  $IPTABLES -P FORWARD ACCEPT
}

case "$1" in
  start)
	echo -n "Setting firewall rules:"
	iptables_start
	echo " done"
	;;
  stop)
	echo -n "Flushing firewall rules:"
	iptables_stop
	echo " done"
	;;
  restart)
	echo -n "Regenerating firewall rules:"
	iptables_stop
	sleep 1
	iptables_start
	echo " done"
	;;
  *)
	echo "Usage: /etc/init.d/firewall {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
